### PR TITLE
xWebConfigKeyValue Cleanup + testing (Fixes #151)

### LINKED ISSUE #151: PSSA rule violations in MSFT_xWebConfigKeyValue
There are no calls to Write-Verbose in Get-TargetResource, Set-TargetResource, or Test-TargetResource
There should be at least one call to Write-Verbose

See rule description here:
(https://github.com/PowerShell/PSScriptAnalyzer/blob/development/RuleDocumentation/ProvideVerboseMessage.md)

### PR DESCRIPTION
**Pull request by tysonjhayes**
Rolled up a bunch of fixes into this push. This should make it way easier for someone to come in and help out with reducing the dependency on AppSettings as the unit tests should help with confirming changes are working/not working.  Integration tests will still need to be added but that can happen in a separate PR. :grin: 

Adding Unit Tests for xWebConfigKeyValue
Added Verbose Statements ( fix #151 cc @mbreakey3 ) and LocalizedData
Added Help Comments
Cleaned up Style to fit within local style guides
Refactored Test-TargetResource to reduce nested if/else statements.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/160)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Looking at your change I think I've encapsalated all of the fixes, unless I'm missing something.

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKoPk1wFVzg525coGh:-KKKoPk1wFVzg525coGi:995572200) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L22)):*
> ```PowerShell
> 
> <#
>     .SNYPOPSIS
> ```

typo - should be .SYNOPSIS

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 56 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKoZqvhTkV6LlAY8PK:-KKKoZqvhTkV6LlAY8PL:643039241) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L56)):*
> ```PowerShell
>             -Message ($LocalizedData.VerboseGetTargetAttributeCheck -f $Key )
> 
>         $existingvalue = Get-ItemValue `
> ```

change to camelCase - $existingValue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 57 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKof6RESsu7Kd6LvfF:-KKKof6RESsu7Kd6LvfG:-1623265788) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L57)):*
> ```PowerShell
> 
>         $existingvalue = Get-ItemValue `
>                             -Key $Key `
> ```

should be -Key #key (lowercase variable name)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 59 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKomTbK8ZcZjGIONJz:-KKKomTbK8ZcZjGIONK-:-1670689869) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L59)):*
> ```PowerShell
>                             -Key $Key `
>                             -IsAttribute $true `
>                             -WebsitePath $WebsitePath `
> ```

again, should be LC variable name - in the one below as well

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 86 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKox48HtVa5PGX5DWd:-KKKox48HtVa5PGX5DWe:-454516873) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L86)):*
> ```PowerShell
> 
> <#
>     .SNYPOPSIS
> ```

typo 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKp-n--7YMyczdwYJ6:-KKKp-n--7YMyczdwYJ7:1670826064) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L102)):*
> ```PowerShell
> 
>         [parameter(Mandatory = $true)]
>         [String] $Key,
> ```

should be $key

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 171 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKp9B_P3orlll5_2fi:-KKKp9B_P3orlll5_2fj:678074825) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L171)):*
> ```PowerShell
> 
> <#
>     .SNYPOPSIS
> ```

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by tysonjhayes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 7 unresolved discussions.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 57 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKof6RESsu7Kd6LvfF:-KKKpq6oH-phx6IVIvVu:-225252998) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L57)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> should be -Key #key (lowercase variable name)
</details>
Going to have to disagree on the lowercase here, it's referencing the parameter variable which should be uppercase. I think for consitency it should be upper case when referring to a parameter and camel case when declared in the function.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 59 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKomTbK8ZcZjGIONJz:-KKKqLwLC2HISbZrRlPW:-225252998) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L59)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> again, should be LC variable name - in the one below as well
</details>
Going to have to disagree on the lowercase here, it's referencing the parameter variable which should be uppercase. I think for consitency it should be upper case when referring to a parameter and camel case when declared in the function.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKp-n--7YMyczdwYJ6:-KKKqN52IfijSLaKyP-_:-225252998) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L102)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> should be $key
</details>
Going to have to disagree on the lowercase here, it's referencing the parameter variable which should be uppercase. I think for consitency it should be upper case when referring to a parameter and camel case when declared in the function.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 215 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKprW5VqzjVeVNwu9W:-KKKprW5VqzjVeVNwu9X:294513911) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L215)):*
> ```PowerShell
>     {
>         if ( ( $null -eq $existingvalue ) -or ( $existingvalue -ne $Value ) `
>                 -or ($existingvalue.Length -eq 0) )
> ```

Again, should be camelCase for variable names - not to be nit picky, but we're trying to use this module as one of our first non-experimental, high-quality resources, so we're cracking down on a lot of the  violations to our style guidelines: 
https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 57 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKof6RESsu7Kd6LvfF:-KKKtgqcTUsx9I8TNjYH:-1673624139) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L57)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Going to have to disagree on the lowercase here, it's referencing the parameter variable which should be uppercase. I think for consitency it should be upper case when referring to a parameter and camel case when declared in the function.
</details>
Ah, yes you're right, I apologize

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 57 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKof6RESsu7Kd6LvfF:-KKKtrZv6PQSYxI0NJo_:-492975247) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L57)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Ah, yes you're right, I apologize
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by tysonjhayes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 22 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKoPk1wFVzg525coGh:-KKPIsalEsTOAfI2CjRd:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L22)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> typo - should be .SYNOPSIS
</details>
Done.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 86 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKox48HtVa5PGX5DWd:-KKPVq77ZNsrsHdzoE8m:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L86)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> typo 
</details>
Done.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 171 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKp9B_P3orlll5_2fi:-KKPVpxGWr4JmXquc1Bm:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L171)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> typo
</details>
Done.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 215 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKprW5VqzjVeVNwu9W:-KKPVs4MZ9zpuDoVRMe8:1434288757) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L215)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Again, should be camelCase for variable names - not to be nit picky, but we're trying to use this module as one of our first non-experimental, high-quality resources, so we're cracking down on a lot of the  violations to our style guidelines: 
> https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md
</details>
I'm fine with nit picky, no worries from me. :grin: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by tysonjhayes** [comment]
@mbreakey3 - this look good to you? I'd like to get it merged so we've got the unit tests.

**Comment by mbreakey3** [comment]
Have the most recent fixes been pushed?

**Comment by tysonjhayes** [comment]
Pushed into the wrong branch, should be good now. :+1:

**Comment by tysonjhayes** [comment]
hey @mbreakey3 - I'd like to try to get this merged before Wednesday's release.

**Comment by mbreakey3** [comment]
@tysonjhayes - no problem. It looks like the changes haven't been pushed though. Could you double check that?

**Comment by mbreakey3** [comment]
Review status: 0 of 4 files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 56 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKoZqvhTkV6LlAY8PK:-KLOLJgvji9KsJ_DmNp8:676834233) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L56)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> change to camelCase - $existingValue
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by mbreakey3** [comment]
Once the merge conflict is fixed, we can merge this too

**Comment by mbreakey3** [comment]
Update on this PR?

**Comment by tysonjhayes** [comment]
@mbreakey3 - could you kick this again? looks like AppVoyer hung.

**Comment by mbreakey3** [comment]
Is this ready to be merged?

**Comment by mbreakey3** [comment]
Reviewed 2 of 3 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Comment by tysonjhayes** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1, line 56 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/160#-KKKoZqvhTkV6LlAY8PK:-KNi-ZnRbtnWih_b1_or:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/14ef5d0dfd8e7e523aca69d0e4ca4037e6882821/DSCResources/MSFT_xWebConfigKeyValue/MSFT_xWebConfigKeyValue.psm1#L56)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> LGTM
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/160)*

**Pull request merged**
