### PR TITLE
xWebApplication: Fixed Set-TargetResource not updating WebAppPool and PhysicalPath

### PR DESCRIPTION
**Pull request by gigi81**
Fixed calls to Set-WebConfigurationProperty in Set-TargetResource when updating PhysicalPath and WebAppPool

### CODE REVIEW

**Comment by gigi81** [comment]
I already signed the CLA so I don't understand why this has been labeled as cla-required

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/220)*

**Comment by mbreakey3** [comment]
Sorry for the inconvenience, but could you try signing the CLA one more time?  https://cla.microsoft.com. It looks like it didn't go through.

**Comment by SNikalaichyk** [comment]
Hi, this change does not seem to work. Can it be reopened/reverted?

**Pull request merged**
