### PR TITLE
RTA: xWebsite Integration tests & fixes

### PR DESCRIPTION
**Pull request by nzspambot**
Hi, added some basic xWebsite integration tests as well as some fixes to xWebsite

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/135)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 101 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-KJr0Cv1BsxwI6W3cBoW:-KJr0Cv241xC7X-viJwW:-80569210) ([raw file](https://github.com/powershell/xwebadministration/blob/5b85ecc2c37f2c62a14e5066cf724874d3e951c0/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L101)):*
> ```PowerShell
> 			Get-WebConfiguration -Filter '//defaultDocument/files/*' -PSPath "IIS:\Sites\$Name" |
> 			ForEach-Object -Process {Write-Output -InputObject $_.value}
> 		)
> ```

Are these tabs (it's showing up as such in reviewable but just want to double check) if so can we please get these switched to spaces.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 105 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-KJr0aiQcaTJXDaUPetw:-KJr0aiQcaTJXDaUPetx:-1798787772) ([raw file](https://github.com/powershell/xwebadministration/blob/5b85ecc2c37f2c62a14e5066cf724874d3e951c0/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L105)):*
> ```PowerShell
> 		$WebSiteAutoStartProviders = (Get-WebConfiguration -filter /system.applicationHost/serviceAutoStartProviders).Collection
> 		$WebConfiguration = $WebSiteAutoStartProviders | `
> 								Where-Object -Property Name -eq -Value $ServiceAutoStartProvider | ` 
> ```

Could we please keep this to four spaces to keep it well under our character limits?

So this would look like:

````powershell
$WebConfiguration = $WebSiteAutoStartProviders | `
    Where-Object -Property Name -eq -Value $ServiceAutoStartProvider | `
    Select-Object Name,Type
````

Instead of:

````powershell
$WebConfiguration = $WebSiteAutoStartProviders | `
                                            Where-Object -Property Name -eq -Value $ServiceAutoStartProvider | `
                                            Select-Object Name,Type
````


I'd want to see this carried through all of the changes we made.

---

*[Tests/Integration/MSFT_xWebsite.config.ps1, line 22 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-KJr14Ht8-8aUEDzirfy:-KJr14Ht8-8aUEDzirfz:1677341763) ([raw file](https://github.com/powershell/xwebadministration/blob/5b85ecc2c37f2c62a14e5066cf724874d3e951c0/Tests/Integration/MSFT_xWebsite.config.ps1#L22)):*
> ```PowerShell
>             ApplicationPool = $Node.ApplicationPool
>             AuthenticationInfo = MSFT_xWebAuthenticationInformation
>                 {
> ```

Could we bring this curly brace back in line with AuthenticationInfo?

---

*[Tests/Integration/MSFT_xWebsite.config.ps1, line 28 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-KJr1UmHhtLrNauutCvm:-KJr1UmIVPktlJHRNFyr:907665659) ([raw file](https://github.com/powershell/xwebadministration/blob/5b85ecc2c37f2c62a14e5066cf724874d3e951c0/Tests/Integration/MSFT_xWebsite.config.ps1#L28)):*
> ```PowerShell
>                     Windows   = $Node.AuthenticationInfoWindows
>             }
>             BindingInfo = @(MSFT_xWebBindingInformation
> ```

Could we please style this like the following? This would bring it back to a consistent four spaces.


````powershell
BindingInfo = @(
    MSFT_xWebBindingInformation
    {
        Protocol              = $Node.HTTPProtocol
        Port                  = $Node.HTTPPort
        IPAddress             = '*'
        Hostname              = $Node.HTTP1Hostname
    }
    MSFT_xWebBindingInformation
    {
        Protocol              = $Node.HTTPProtocol
        Port                  = $Node.HTTPPort
        IPAddress             = '*'
        Hostname              = $Node.HTTP2Hostname
    }
    MSFT_xWebBindingInformation
    {
        Protocol              = $Node.HTTPSProtocol
        Port                  = $Node.HTTPSPort
        IPAddress             = '*'
        Hostname              = $Node.HTTPSHostname
        CertificateThumbprint = $CertificateThumbprint
        CertificateStoreName  = $Node.CertificateStoreName
        SslFlags              = $Node.SslFlags
    }
)
````

---

*[Tests/Integration/MSFT_xWebsite.config.ps1, line 83 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-KJr1emxEKlKHT6IZoxr:-KJr1emxEKlKHT6IZoxs:1237609764) ([raw file](https://github.com/powershell/xwebadministration/blob/5b85ecc2c37f2c62a14e5066cf724874d3e951c0/Tests/Integration/MSFT_xWebsite.config.ps1#L83)):*
> ```PowerShell
>             ApplicationPool = $Node.ApplicationPool
>             AuthenticationInfo = MSFT_xWebAuthenticationInformation
>                 {
> ```

See above for this line.

---

*[Tests/Integration/MSFT_xWebsite.config.ps1, line 89 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-KJr1g5-MVsIi2QOR62o:-KJr1g5-MVsIi2QOR62p:-98624438) ([raw file](https://github.com/powershell/xwebadministration/blob/5b85ecc2c37f2c62a14e5066cf724874d3e951c0/Tests/Integration/MSFT_xWebsite.config.ps1#L89)):*
> ```PowerShell
>                     Windows   = $Node.AuthenticationInfoWindows
>             }
>             BindingInfo = @(MSFT_xWebBindingInformation
> ```

See above for this line

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/135)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 2 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/135)*

**Comment by tysonjhayes** [comment]
:frowning: - we can focus on getting the logic (and unit tests) working and I can try to help with the merge.

<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> Now I'm in merge hell :cry: 
</details>


---

Reviewed 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-:-KKBGPE7E8XRDyefw1Mk:-2013703218)*

**Comment by mbreakey3** [comment]
Could you make sure all of the $null variables are on the left-hand side of the comparison?

**Comment by mbreakey3** [comment]
Anywhere where a variable is being compared to $null (-eq, -ne, etc.) $null should be on the left-hand side. These were changes made in #141 and it looks like some of them got overwritten in the merge-conflict.

**Comment by tysonjhayes** [comment]
:lgtm:

---

Reviewed 2 of 3 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/135#-:-KKKcnzwj4jLkMUiG2D6:1417088721)*

**Pull request merged**
