### PR TITLE
Style fixes

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/159)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1, line 117 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/159#-KKF82EuQoQBJ10LSVxH:-KKF82EuQoQBJ10LSVxI:-223562924) ([raw file](https://github.com/powershell/xwebadministration/blob/3d0f42015843110bfd1c65627e69a58df66800c1/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L117)):*
> ```PowerShell
> }
> 
> # some internal helper function to do the actual work:
> ```

why are we removing regions?

---

*[DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1, line 124 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/159#-KKF8KmTZ_65OPgd0pPd:-KKF8KmTZ_65OPgd0pPe:1885827497) ([raw file](https://github.com/powershell/xwebadministration/blob/3d0f42015843110bfd1c65627e69a58df66800c1/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L124)):*
> ```PowerShell
>     if (!$newValue)
>     {
>         return
> ```

Fix merge conflicts

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/159)*

**Comment by mbreakey3** [comment]
*[DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1, line 117 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/159#-KKF82EuQoQBJ10LSVxH:-KKFCJkUXLSYvSqdXrr0:444236094) ([raw file](https://github.com/powershell/xwebadministration/blob/3d0f42015843110bfd1c65627e69a58df66800c1/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L117)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>
> why are we removing regions?
</details>
Where were they removed? I was just cleaning up the comment style so the code is more polished

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/159)*

**Comment by tysonjhayes** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/159)*

**Comment by TravisEz13** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1, line 117 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/159#-KKF82EuQoQBJ10LSVxH:-KK_F_R4GOOf3cRTH0b3:-890079708) ([raw file](https://github.com/powershell/xwebadministration/blob/3d0f42015843110bfd1c65627e69a58df66800c1/DSCResources/MSFT_xWebAppPoolDefaults/MSFT_xWebAppPoolDefaults.psm1#L117)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Where were they removed? I was just cleaning up the comment style so the code is more polished
</details>
looks good now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/159)*

**Comment by TravisEz13** [comment]
Reviewed 8 of 10 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/159)*

**Pull request merged**
