### PR TITLE
Fixing up PR 248 to pass

### PR DESCRIPTION
**Pull request by tysonjhayes**
I've been wanting to merge #248 but the integration tests weren't passing. So I took the liberty of fixing it up to pass.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/272)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 5 of 7 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Examples/Sample_xWebAppPoolDefaults.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_16bxByuANAiOO_kRK:-K_16bxByuANAiOO_kRL:bdf15i2) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebAppPoolDefaults.ps1#L2)):*
> ```PowerShell
> <#
> .SYNOPSIS
> ```

Could you indent everything within the block comment 

---

*[Examples/Sample_xWebConfigKeyValue_AddAppSetting.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_16rIEa2C0rz8lrz95:-K_16rIEa2C0rz8lrz96:b-hm00j4) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebConfigKeyValue_AddAppSetting.ps1#L2)):*
> ```PowerShell
> <#
> .SYNOPSIS
> ```

Indent comment

---

*[Examples/Sample_xWebConfigKeyValue_RemoveAppSetting.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_174iV1NUQnO8FCP0e:-K_174iV1NUQnO8FCP0f:b-11ftn4) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebConfigKeyValue_RemoveAppSetting.ps1#L2)):*
> ```PowerShell
> <#
> .SYNOPSIS
> ```

indent comment

---

*[Examples/Sample_xWebSiteDefaults.ps1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_17Hhs3rQBOn8naIHo:-K_17Hhs3rQBOn8naIHp:b-w8miv6) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebSiteDefaults.ps1#L3)):*
> ```PowerShell
> <#
> .SYNOPSIS
>     An example of configuring the website default settings.
> ```

indent comment.

---

*[Tests/Integration/MSFT_xWebConfigKeyValue.Integration.Tests.ps1, line 48 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_17l2j0WZZJhuBYU6C:-K_17l2j0WZZJhuBYU6D:b-257hag) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Tests/Integration/MSFT_xWebConfigKeyValue.Integration.Tests.ps1#L48)):*
> ```PowerShell
>         #endregion
> 
>         It 'Updating AppSetting "xWebAdministration Integration Tests Key"' {
> ```

Each of these 'It' statements should start with:   It 'Should.....'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/272)*

**Comment by tysonjhayes** [comment]
Review status: 5 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests/Integration/MSFT_xWebConfigKeyValue.Integration.Tests.ps1, line 48 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_17l2j0WZZJhuBYU6C:-K_8Wm6XoFqcFDQBfXsN:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Tests/Integration/MSFT_xWebConfigKeyValue.Integration.Tests.ps1#L48)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

Each of these 'It' statements should start with:   It 'Should.....'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/272)*

**Comment by mbreakey3** [comment]
Reviewed 4 of 4 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/272)*

**Comment by kwirkykat** [comment]
@mbreakey3 Done with review or still waiting?

**Comment by mbreakey3** [comment]
@kwirkykat  - still a couple minor changes

**Comment by tysonjhayes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Examples/Sample_xWebConfigKeyValue_AddAppSetting.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_16rIEa2C0rz8lrz95:-KbCaNKbJcuZmx4OWkvN:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebConfigKeyValue_AddAppSetting.ps1#L2)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

Indent comment
</blockquote></details>

Done.

---

*[Examples/Sample_xWebConfigKeyValue_RemoveAppSetting.ps1, line 2 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_174iV1NUQnO8FCP0e:-KbCaMXEGA-KEZ0tY-WP:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebConfigKeyValue_RemoveAppSetting.ps1#L2)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

indent comment
</blockquote></details>

Done.

---

*[Examples/Sample_xWebSiteDefaults.ps1, line 3 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-K_17Hhs3rQBOn8naIHo:-KbCaMxqePfFy5RStiom:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/df092adb3569fa51684062b187472b8ed24bb89c/Examples/Sample_xWebSiteDefaults.ps1#L3)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

indent comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/272)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/272#-:-KbCfWMHoZ3tGx43V_LP:bnfp4nl)*

**Comment by mbreakey3** [comment]
Just need to fix the failing tests

**Comment by kwirkykat** [comment]
@tysonjhayes @mbreakey3  Seems that the tests are having a problem with the new Pester version 4 released last week. @nzspambot opened an issue for Pester about this already: https://github.com/pester/Pester/issues/702

**Comment by tysonjhayes** [comment]
This does look like a repo of the bug reported by @nzspambot.

**Comment by mbreakey3** [comment]
Just merged a PR that should fix the Pester failures - if you rebase this should pass now

**Comment by tysonjhayes** [comment]
Closing this as a broke the git history trying to rebase and have no idea how to fix it. I've just opened a new branch and redid the changes (as it was only a few).

**Pull request closed without merging**
