### PR TITLE
Adding xSSLSettings resource

### PR DESCRIPTION
**Pull request by tysonjhayes**

### CODE REVIEW

**Comment by tysonjhayes** [comment]
If anyone wants to comment feel free.

**Comment by TravisEz13** [comment]
@tysonjhayes 
Please update the readme and include a summary of changes in an unreleased version change per the [contribution guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#lifecycle-of-a-pull-request)

Other than that, it looks good.

**Comment by tysonjhayes** [comment]
Would like to try to add an integration test for this just to button it up. Will try to get to it within the next few days.

**Comment by TravisEz13** [comment]
Thanks Tyson!

**Comment by tysonjhayes** [comment]
I'm going to open an issue for the integration tests as I haven't had time.

**Pull request merged**
