### PR TITLE
xWebSite: Resolve Resource Name Case

### LINKED ISSUE #535: xWebSite: Resolve casing in name
There are files and folders that are named `Website` instead of `WebSite`(upper-case 'S'). Also code referencing `Website` should be changed to `WebSite`.

Throughout the repository.

### PR DESCRIPTION
**Pull request by RandomNoun7**
Prior to this change the case used in the resource name `xWebsite` was
inconsistant and should have been `xWebSite` in all instances.

- Fixes #535

- [x] Added an entry to the change log under the Unreleased section of the CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [x] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/538)

### CODE REVIEW

**Comment by RandomNoun7** [comment]
This PR contains the commit from #537.

Once 537 is merged I think a quick close and reopen of this PR will drop the earlier commit from the commit list because github will recognize that the sha from 537 is already in the history.

If it doesn't feel free to ping me and I'll do a manual rebase.

**Comment by RandomNoun7** [comment]
Also, Github's UI doesn't make it the easiest thing to see, but the way to verify that I'v done file moves in a way that will stick in the repository is to look at the name of the file in the diff view. If you see a filename, and then a little arrow and another file name, it means the file name was moved from the former to the latter.
image

**Comment by johlju** [comment]
I use Reviewable to review, so it clearly shows the renamed files. :)

image

**Comment by RandomNoun7** [comment]
@johlju Oops. Not sure how I did all those edits and then forgot to rename those files, but it's fixed now.

**Comment by johlju** [comment]
@RandomNoun7 Thank you for this! 😃

**Pull request merged**
