### PR TITLE
Release of version 2.6.0.0 of xWebAdministration

### PR DESCRIPTION
**Pull request by kwirkykat**
Releasing version 2.6.0.0

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/421)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@tysonjhayes @regedit32 @gaelcolas Release of this module is blocked by failing tests. Looks like PSSA errors. Let me know when it's fixed and then release can move forward.

**Comment by johlju** [comment]
@kwirkykat There is a reported bug in PSScriptAnalyzer for that https://github.com/PowerShell/PSScriptAnalyzer/issues/1192. Once that is merged and a new release of PSScriptAnalyzer is made we can move forward with this. If we want to release this prior we should change the test framework to use an older version of PSScriptAnalyzer.

/cc @gaelcolas @PlagueHO @ykuijs

**Comment by ykuijs** [comment]
There is a workaround : move the super class to the top of the schema file. PSSA is only checking the first class in the schema.

**Comment by regedit32** [comment]
I'll take this for action and apply the PSSA rule suppression until the fix to PSScriptAnalyzer is released

**Comment by regedit32** [comment]
fix merged to dev branch

**Pull request merged**
