### PR TITLE
xWebAdministration: Adding resource ToC to README.md

### LINKED ISSUE #450: Add a a ToC to the resource section in the README.md
We should add a ToC to the top of the resource section in the README.md, before all the individual resource sections. The Table of Contents should look similar to this example https://github.com/PowerShell/SqlServerDsc#resources. The Table of Contents should be in alphabetical order and have a link to each individual resource section.

This should replace the list at the top a line 3 https://github.com/PowerShell/xWebAdministration/blame/dev/README.md#L3

### PR DESCRIPTION
**Pull request by midacts**
Fixes #450

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/503)

### CODE REVIEW

**Comment by midacts** [comment]
[Should not have errors in any markdown files](https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L926)
Any ideas why this test is causing the build to fail?

**Comment by johlju** [comment]
@midacts Will help look at the tests

**Comment by midacts** [comment]
Mission complete

**Comment by midacts** [comment]
Thanks for your help on this and opening these up for me to contribute for Hacktoberfest.

**Pull request merged**
