### PR TITLE
XWebAdministration: OptIn to DSC Resource Meta Tests

### PR DESCRIPTION
**Pull request by X-Guardian**
#### Pull Request (PR) description

This PR opts in to the following DSC Resource meta tests:

- Common Tests - Relative Path Length
- Common Tests - Validate Script Files
- Common Tests - Validate Module Files
- Common Tests - Validate Markdown Files
- Common Tests - Validate Markdown Links

To pass the `Common Tests - Validate Script Files`, the following files had their BOM mark removed:

- Examples/Sample_xWebApplication.ps1
- Tests/MockWebAdministrationWindowsFeature.psm1
- Tests/Unit/MSFT_xIisMimeTypeMapping.Tests.ps1
- Tests/Unit/MSFT_xWebApplication.Tests.ps1

To pass the `Common Tests - Validate Markdown Files`, the following files had their markdown fixed:

- HighQualityResourceKitPlan.md
- README.md

This helps move the module towards passing the HQRM requirements.

#### This Pull Request (PR) fixes the following issues

None

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/429)

### CODE REVIEW

**Comment by X-Guardian** [comment]
Can someone review this PR?

**Comment by X-Guardian** [comment]
Can we get this PR merged?

**Comment by PlagueHO** [comment]
Do you want to tag the maintainers directly? I'm not sure Tyson is about these days and cant recall who else is maintaining this.

**Comment by X-Guardian** [comment]
@regedit32, are you able to merge this PR?

**Pull request merged**
