### PR TITLE
xWebApplication: Move localization strings to strings.psd1 file #468

### PR DESCRIPTION
**Pull request by omiossec**
#### Pull Request (PR) description
xWebApplication: Move localization strings to strings.psd1 file

#### This Pull Request (PR) fixes the following issues
   - fixe: #468 

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/520)

### CODE REVIEW

**Comment by johlju** [comment]
Please update this PR similar to https://github.com/PowerShell/xWebAdministration/pull/514.

**Comment by omiossec** [comment]
Just updated 

> Please update this PR similar to #514.

Done

**Comment by omiossec** [comment]
The code coverage fail 
I am trying to see why

**Comment by johlju** [comment]
@omiossec Sometimes it reports false negatives. I don't see any change you did that should change the coverage. So just ignore it. 🙂

**Comment by johlju** [comment]
@omiossec Please update the change log similar to other entries (see example of them referencing the issue being resolved)

**Comment by omiossec** [comment]
> @omiossec Please update the change log similar to other entries (see example of them referencing the issue being resolved)

Done, 

Thank you for your help

**Comment by johlju** [comment]
@omiossec Thank you for this! Please update the other PRs the same way.

**Pull request merged**
