### PR TITLE
Merger PHO cWebsite to xWebsite

### PR DESCRIPTION
**Pull request by zuehlaa**
This merges the work done on Powershell.orgs cWebsite resource https://github.com/PowerShellOrg/cWebAdministration/tree/master/DSCResources/PSHOrg_cWebsite.  There was an issue with xWebsite default page option that I haven't been able to track down.  So I removed that option since it can also be accomplished by using the webConfigProp settings.

### CODE REVIEW

**Comment by vors** [comment]
Please, fix tests. [Running common tests locally](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#run-common-tests-locally)

**Comment by kevinsea** [comment]
The web configuration properties in this merge request have type cast issues.  I found it did not work for many properties I was trying to test.  I have a pull request pending in the powershell.org repo that fixes the problems I found.  It is big change, but it may be a better merge source.

https://github.com/PowerShellOrg/cWebAdministration/pull/21

**Comment by tysonjhayes** [comment]
Hi @zuehlaa - are you still working on this? It's been a while since we've seen any activity on this. If you are not working on this anymore (or I don't hear from you) I'm going to fork this and try to fix it up myself as we'd really like some of this functionality. Please let me know.

**Comment by zuehlaa** [comment]
I've been waiting to hear back from @KarolKaczmarek or @TravisEz13 on https://github.com/PowerShell/xWebAdministration/pull/7#issuecomment-158173354 before doing any more work on this one

**Comment by tysonjhayes** [comment]
Thanks, as noted in the other PR if you could get the merge conflicts resolve and this updated I'll try to help you get this sorted out.

**Comment by TravisEz13** [comment]
@tysonjhayes @zuehlaa I reviewed the other mentioned PR.  I'm not sure what this is waiting on.  So, I'll comment on the issues that I see.

@zuehlaa 
Please resolve merge conflicts.  For more information see [GitHowTo - 30. Resolving Conflicts](http://githowto.com/resolving_conflicts )


It is required that you provide adequate test coverage for the code **you change**. [Contribution Guidelines -Adding test coverage for DSC resources](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#adding-test-coverage-for-dsc-resources)  Please work with us to come up with a plan to cover this code.

If there is no update of the pull request within 7 days, we will close the pull request.  After that, if you have an update, feel free to reopen the pull request.

**Comment by TravisEz13** [comment]
Closing because the pull request has not been updated for feedback given for 21 days.  Once you update the code, please feel free to reopen the pull request.  Thanks, Travis.

**Pull request closed without merging**
