### PR TITLE
RTA: xSMTP

### PR DESCRIPTION
**Pull request by nzspambot**
Ok here is a 95%(?) complete xSMTP resource

**Things to do**
- ~~add more unit tests for the helper function~~ e: Added these tests
- validate sets on the param inputs

**Things which don't work**
- Some settings refuse to be set. It maybe because other params are outside acceptable ranges but unsure at this stage. Needs more investigation. As a result appveyor should not work.
- As mentioned the logging is interesting there seems on the face of it no way to enable logging which renders the logging options moot

**Things to note**
- All params (bar one) are [String] as if cast as say [Int] the `Get-TargetResource` in the integration tests will take a :hankey:

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/162)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Not to be a pest but would it be possible to call it SMTPServer or SMTPHost or something to clarify what its purpose is?

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 30 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 11 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKeAXDwNOSgE4D4zAk:-KKKeAXDwNOSgE4D4zAl:-1657011491) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L11)):*
> ```PowerShell
>     # culture="en-US"
>     ConvertFrom-StringData -StringData @'
> ErrorSMTPDiscoveryFailure = No SMTP Virutal server found.
> ```

Going to need to add four spaces to all of these or @mbreakey3 will come scowl at you.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 91 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKePFhHbcfJa9gFpB7:-KKKePFhHbcfJa9gFpB8:-1933677064) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L91)):*
> ```PowerShell
>     (
>         [Parameter(Mandatory = $true)]
>         [ValidateSet('1')]
> ```

~~I'm not sure I understand this ValidateSet what's this doing? ~~  Why are we limiting ourselves to the default SMTP? Couldn't we be managing multiple SMTP servers?

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 256 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKfVZ8DVtrI-AEoCUo:-KKKfVZ9QlItA5gpxpSC:390574915) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L256)):*
> ```PowerShell
> 
>     #Update AuthFlags if required
>     if (($PSBoundParameters.ContainsKey('AuthFlags') -and `
> ```

So just a thought here, could we possibly do a loop instead of each check individually?

You could use the following code as a basis: https://github.com/PowerShell/xNetworking/blob/dev/DSCResources/MSFT_xFirewall/MSFT_xFirewall.psm1#L41

Then we could do something like:

````powershell
foreach ($parameter in $ParameterList)
{
    if ($PSBoundParameters.ContainsKey($Parameter) -and $Result.$Parameter -ne $PSBoundParameter[$Parameter]
    {
        Write-Verbose -Message "Updated SMTPSetting {0} from {1} to {2}" -f $Parameter, $Result.$Parameter, $PSBoundParameter[$Parameter]
         Set-SMTPSettings `
            -Name $Name `
            -Setting $Parameter
            -Value $PSBoundParameter[$Parameter]
    }
}

````

This would cover all of the setting/checking and break it down into a more "simple"* loop. 


* Obviously would require testing but it reduces the amount if checks we're writing. :grin: 

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 257 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKeg7JG9zgbTc0Zude:-KKKeg7JG9zgbTc0Zudf:-1161182198) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L257)):*
> ```PowerShell
>     #Update AuthFlags if required
>     if (($PSBoundParameters.ContainsKey('AuthFlags') -and `
>     $Result.AuthFlags -ne $AuthFlags))
> ```

Could we move this over four spaces?

````powershell
if (($PSBoundParameters.ContainsKey('AuthFlags') -and `
    $Result.AuthFlags -ne $AuthFlags))
{
    #code stuff
}
````

Actually you can assume that I'd like to see this all the way down.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 272 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKiDVtbI1bMy2BLqBs:-KKKiDVtbI1bMy2BLqBt:-989961972) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L272)):*
> ```PowerShell
>         {
>             $ErrorMessage = $LocalizedData.ErrorBadMailDirectoryFailure
>             New-TerminatingError -ErrorId 'BadMailDirectoryFailure' `
> ```

Are we being proactive or does this actually fail if the folder doesn't exist?

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 717 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKiPO3nK5iDClccmXy:-KKKiPO3nK5iDClccmXz:-899338130) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L717)):*
> ```PowerShell
>     #Update AuthFlags if required
>     if (($PSBoundParameters.ContainsKey('AuthFlags') -and 
>     $Result.AuthFlags -ne $AuthFlags))
> ```

Same comments for Set-TargetResource as for here as a way to tighten up the loop of things we can do.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1009 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKiYSHd3jU29zuqg9J:-KKKiYSHd3jU29zuqg9K:-9309617) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1009)):*
> ```PowerShell
> Function Confirm-UnqiueBindings
> {
>     <#
> ```

I think the style is to have this outside of the function? Honestly I'm not sure here but you need at least four more spaces.

````powershell
<#
    .SYNOPSIS
#>
````

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1029 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKihELluUf_Z8ASERt:-KKKihELluUf_Z8ASERu:1673779956) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1029)):*
> ```PowerShell
>         [String]
>         $ExistingBindings,
>         
> ```

tab I think?

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1042 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKit-zqnpLLGhIGrq-:-KKKit-zqnpLLGhIGrq0:-1794041056) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1042)):*
> ```PowerShell
>     }
> 
>     $ExistingBindingssToCheck = $ExistingBindings -split '\n'
> ```

Think you got to many ss here. I think your variable should probably be $ExistingBindingsToCheck (note one less s)

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1050 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKj16HRVi00z8bX_Xg:-KKKj16HRVi00z8bX_Xh:-1357113797) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1050)):*
> ```PowerShell
>     }
> 
>     $SortedExistingBindings = $ExistingToCheck | Sort-Object -Unique
> ```

Think we can just get away with doing:

````powershell
$ExistingToCheck = $ExistingToCheck | Sort-Object -Unique
$InputToCheck = $InputToCheck | Sort-Object -Unique
````

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1124 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKk6YoXyID8EbTkbWH:-KKKk6YpYZPevOkURjm0:-2069126790) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1124)):*
> ```PowerShell
> Function Test-EmailAddress
> {
>         <#
> ```

Missalinged comment.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1136 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKk8JfP0uFwWQqSs1Y:-KKKk8JglXSfbO_xp8sI:677097967) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1136)):*
> ```PowerShell
>     [CmdletBinding()]
>     param(
>         
> ```

Tab?

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1143 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkC6kvFy-1lCJnRhA:-KKKkC6l58bWg1TgXIY7:-1532443942) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1143)):*
> ```PowerShell
>     )
>     
>     if($Email)
> ```

Email is mandatory shouldn't this always be true? And if so why do we need it?

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1148 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkJZyd50jlmJas-g6:-KKKkJZyd50jlmJas-g7:-2073230988) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1148)):*
> ```PowerShell
>         {
>             $ErrorMessage = $LocalizedData.ErrorEmailAddressFailure
>             New-TerminatingError -ErrorId 'EmailAddressFailure' `
> ```

If our output is supposed to be a boolean why are we throwing here?

Personal preference, test- cmdlets shouldn't throw only return true/false.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1183 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkW0-J9Oe0Hc--vpO:-KKKkW0-J9Oe0Hc--vpP:-1571256487) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1183)):*
> ```PowerShell
> 
>     foreach ($Binding in $ServerBindings)
> ```

Could you remove this space here please.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1193 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkjfdOky6mpxAWF7C:-KKKkjfdOky6mpxAWF7D:923743503) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1193)):*
> ```PowerShell
>             {
>                 $ErrorMessage = $LocalizedData.ErrorIPAddressFailure
>                 New-TerminatingError -ErrorId 'IPAddressFailure' `
> ```

Also do we need to terminate here? Could we just return false?

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1212 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkcc9DH3yNss7EHpA:-KKKkcc9DH3yNss7EHpB:-1981731714) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1212)):*
> ```PowerShell
>         }
> 
>         return $true
> ```

I think if you have multiple ServerBindings wouldn't this exist the function before all of them have been tested? I think you want to move your return $true outside of the foreach loop.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.schema.mof, line 4 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkoHDUAJ4uAvKDSC8:-KKKkoHDUAJ4uAvKDSC9:-599852433) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.schema.mof#L4)):*
> ```
> class MSFT_xSMTP : OMI_BaseResource
> {
>     [Key] UInt16 ID;
> ```

I'm not seeing $name in the schema, should this be $name and not $id?

---

*[Tests/Integration/MSFT_xSMTP.config.ps1, line 45 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKjx2MzCZtiOkPRKoC:-KKKjx2MzCZtiOkPRKoD:2094245238) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.config.ps1#L45)):*
> ```PowerShell
>         }
>     }
> }
> ```

Need a new line here.

---

*[Tests/Integration/MSFT_xSMTP.config.psd1, line 5 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKjo25qaD8whZXvmcJ:-KKKjo25qaD8whZXvmcK:84608005) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.config.psd1#L5)):*
> ```PowerShell
>     AllNodes = @(
>         @{
>                 Name                             = '1'
> ```

Does tthis not work if we have it as:

````powershell
Name = 1
````

That would cast it as an int instead of a string.

---

*[Tests/Integration/MSFT_xSMTP.config.psd1, line 40 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKjvH-QYptRR1mwU0L:-KKKjvH0ZnNCOKuHdUaV:2094245238) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.config.psd1#L40)):*
> ```PowerShell
>         }
>     )
> }
> ```

Need a new line here.

---

*[Tests/Integration/MSFT_xSMTP.Integration.tests.ps1, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKl-arOfrC1sCke5we:-KKKl-arOfrC1sCke5wf:-1151097586) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.Integration.tests.ps1#L28)):*
> ```PowerShell
>     . $ConfigFile
> 
>     $null = Backup-WebConfiguration -Name $tempName
> ```

Could we backup the web config before loading the config file please?

---

*[Tests/Integration/MSFT_xSMTP.Integration.tests.ps1, line 47 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKlHIl2U9qbU-xbspD:-KKKlHIl2U9qbU-xbspE:678051279) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.Integration.tests.ps1#L47)):*
> ```PowerShell
> 
>         It 'Should create a WebApplication with correct settings' -test {
>             
> ```

tab?

---

*[Tests/Integration/MSFT_xSMTP.Integration.tests.ps1, line 100 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKlLpFmJMr6OLK1q87:-KKKlLpFmJMr6OLK1q88:-1596761833) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.Integration.tests.ps1#L100)):*
> ```PowerShell
>     Restore-TestEnvironment -TestEnvironment $TestEnvironment
>     #endregion
> }
> ```

New line here

---

*[Tests/Unit/MSFT_xSMTP.tests.ps1, line 14 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKlOYDvgnaC2NAYjZM:-KKKlOYDvgnaC2NAYjZN:-396898603) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Unit/MSFT_xSMTP.tests.ps1#L14)):*
> ```PowerShell
> Import-Module (Join-Path -Path $moduleRoot -ChildPath 'DSCResource.Tests\TestHelper.psm1') -Force
> $TestEnvironment = Initialize-TestEnvironment `
> -DSCModuleName $global:DSCModuleName `
> ```

Need some tabs here 

---

*[Tests/Unit/MSFT_xSMTP.tests.ps1, line 24 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKlSFpZ1K9roZrte0n:-KKKlSFpZ1K9roZrte0o:-455245156) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Unit/MSFT_xSMTP.tests.ps1#L24)):*
> ```PowerShell
> {
>     #region Pester Tests
>     
> ```

tabs?

---

*[Tests/Unit/MSFT_xSMTP.tests.ps1, line 325 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKmj_Nx4Nu3exU7uSr:-KKKmj_Nx4Nu3exU7uSs:-2082271177) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Unit/MSFT_xSMTP.tests.ps1#L325)):*
> ```PowerShell
>             }
> 
>             Context 'All Settings are incorrect' {
> ```

I'm not sure this is doing what you think it is. Because you are doing a return $false this would return out on the first check and be done, so it doesn't really matter that all of them are wrong it's only checking the first one. I'm not sure this is actually valuable.

---

*[Tests/Unit/MSFT_xSMTP.tests.ps1, line 347 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKmvawpebH82gcP28k:-KKKmvawpebH82gcP28l:981117710) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Unit/MSFT_xSMTP.tests.ps1#L347)):*
> ```PowerShell
>                 $Result = Test-TargetResource -Name $MockParamaters.Name -AuthFlags $MockParamaters.AuthFlags
> 
>                 It 'should return False' {
> ```

So consider this advice for all of these.  I would consider adding a check for the verbose message to validate you are hitting the line you think you are.  In your code you do a return $false the first time you run into something that's wrong, which imo is good practice no sense in checking the rest of it.

This would be tested like this:

````powershell
$Result = Test-TargetResource -Name $MockParamaters.Name -AuthFlags $MockParamaters.AuthFlags -Verbose 4>&1

It 'should return False' {
    $Result[0] | Should Be $false
}

It 'should return the correct message' {
   $result[1] | Should Be $LocalizedData.VerboseTestTargetFalseAuthFlags
}
````

---

*[Tests/Unit/MSFT_xSMTP.tests.ps1, line 817 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKm8pP1xbc5JibJm9N:-KKKm8pP1xbc5JibJm9O:1899073310) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Unit/MSFT_xSMTP.tests.ps1#L817)):*
> ```PowerShell
>             Context 'AuthFlags exists but needs to be updated' {
> 
>                 Mock -CommandName Get-SMTPSettings -MockWith {
> ```

Your spacing gets all of from about here down in the code.  Your closing brace should line up with Mock and all functions below it should line up as well. Might want to take a pass through this.

---

*[Tests/Unit/MSFT_xSMTP.tests.ps1, line 821 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKoAiEcYZqTi9q4qQa:-KKKoAiEcYZqTi9q4qQb:-1633915356) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Unit/MSFT_xSMTP.tests.ps1#L821)):*
> ```PowerShell
>                         }
> 
>                     Mock -CommandName Set-SMTPSettings
> ```

I would consider adding ParameterFilter to the mock, here we're not 100% sure we've called the right thing at the right time. This would look like.

````powershell
Mock Set-SMTPSettings {}
Mock -CommandName Set-SMTPSettings -ParameterFilter { $Setting -eq 'AuthFlags' -and $Value -eq $MockParameters.AuthFlags}

It 'should call the expected mocks' {
    $Result = Set-TargetResource -Name $MockParamaters.Name -AuthFlags $MockParamaters.AuthFlags

    Assert-MockCalled -CommandName Set-SMTPSettings -Exactly 0
    Assert-MockCalled -CommandName Set-SMTPSettings  -ParameterFilter { $Setting -eq 'AuthFlags' -and $Value -eq $MockParameters.AuthFlags} -Exactly 1
}
````

This is not only validating that you called the right function with the right call but you didn't call it some other way.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-:-KKKe26l8gTzd7Nc8huf:94155887)*

**Comment by tysonjhayes** [comment]
Review status: 1 of 7 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 272 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKiDVtbI1bMy2BLqBs:-KKPFKSINnYBF1PHU_mK:1581076654) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L272)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> It will fail to start if the folder doesn't exist yes.
</details>
Is the error message unclear when it tries to set it or is there a value in us failing it out? Personally I'm not a fan of doing much error handling preferring to push it down as low as I can. If the error message is unclear as to whats happen I'm totally a fan of adding this.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1029 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKihELluUf_Z8ASERt:-KKPFe-4AXqbxr2rLJdy:-1872082591) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1029)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> no those are spaces
</details>
Yeah I'll stop point it out.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1143 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkC6kvFy-1lCJnRhA:-KKPG1Wkes7Bwg3VqbPI:1368079659) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1143)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> if email is ok then this will work; this just checks the email is ok
</details>
I'm not sure I'm being clear here. We have to specifiy a value for $Email, you appear to be testing that there is a value for $Email before evaluating if $Email is formatted as a mailing address. I don't think we need to check if $Email has a value because if it is null it wouldn't pass the next check.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1148 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkJZyd50jlmJas-g6:-KKPGUIxIrUgBGnAucOn:2065735413) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1148)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> because I want to return to the user any issues, helps troubleshooting. Returning a false hides errors
</details>
Then I would say this should return false and we capture the error outside of the function. So that'd be like:

````powershell
if (Test-EmailAddress -EmailAddress 'Notagoodemail.com')
{
    # do whatever
}
else
{
    # throw terminatingerror here
}
````

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1193 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkjfdOky6mpxAWF7C:-KKPGrtj6b7vG23084m_:-1106735725) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1193)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> because I want to return to the user any issues, helps troubleshooting. Returning a false hides errors
</details>
See my notes on test-emailaddress

---

*[Tests/Integration/MSFT_xSMTP.config.psd1, line 5 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKjo25qaD8whZXvmcJ:-KKPH00NYb2CyDCs38LT:182774538) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.config.psd1#L5)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> nope, default is [string] so this will be a string
</details>
I guess why is it a string versus an int then? You mentioned something about it being :shit: for the integration tests but I wasn't really following what was going on. Could you help me understand?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/162)*

**Comment by tysonjhayes** [comment]
Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/162)*

**Comment by tysonjhayes** [comment]
Review status: 5 of 7 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 272 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKiDVtbI1bMy2BLqBs:-KKp_oLvTWbnW6j5RBpQ:1137309818) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L272)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> Well in testing you can set anything you like but if you then go into the console it will fail to start an you will only (I think) find out it is a directory issue once you hit the correct page in the settings
</details>
I guess I'm asking if you specifiy a bad directory without this test path what happens? What error messages does it give you, if any? If it has none then yeah let's have this throw something, else lets evaluate what its saying to see if we're adding value.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1143 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkC6kvFy-1lCJnRhA:-KKpZ_BOEMdvtqHeU77U:-325188278) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1143)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> I'm a bit lost here. If there is no email in the Test then yes it will never test it. If there is an email then we test that the email is valid 
> . Thats what I was aiming for
</details>
Basically checking if $Email has a value doesn't seem valuable to me, and I guess I'm recommending we remove it. If you want to make sure it has a value I would add some parameter validation.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 1148 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKkJZyd50jlmJas-g6:-KKp_OpV3TSqXzF936rA:1898094294) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L1148)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> If you want that then you could do away with the test function and cast -as in the if{} then
> 
> I personally like the idea of subfunctions which are $true/$false and error
</details>
Personally I write my code like that. This just seems like we're adding more layers where there doesn't really need to be, just my thoughts though.

---

*[Tests/Integration/MSFT_xSMTP.config.psd1, line 5 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKKjo25qaD8whZXvmcJ:-KKpZJhvBC9KfPgz8_cH:-603817870) ([raw file](https://github.com/powershell/xwebadministration/blob/6f38aef8bfbd550fbf7caadbda3b4a851278a9c0/Tests/Integration/MSFT_xSMTP.config.psd1#L5)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> Yeah so in testing DSC is applied correctly however if you run a Get-DSCConfiguration that will bomb out. Digging through it is because the [ASDI] params are a (OTTOMH) a dictionary type which would not cast to [int] would only cast to [string]
</details>
That makes perfect sense. Could we make a note... somewhere? Maybe in the mof file or something so we don't try to "correct" this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/162)*

**Comment by tysonjhayes** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1, line 359 \[r4\]](https://reviewable.io:443/reviews/powershell/xwebadministration/162#-KKpaduWYbPnMi8mPkqS:-KKpaduWYbPnMi8mPkqT:1904815046) ([raw file](https://github.com/powershell/xwebadministration/blob/f7f68b8b50c4c1a161ce29547509bf3478fb77c2/DSCResources/MSFT_xSMTP/MSFT_xSMTP.psm1#L359)):*
> ```PowerShell
>                     <#
>                      Bug?
>                      Blank to since name does not need to be set
> ```

You can remove the parameter and make a note saying we don't need to specify it.  I'd do this before the loop.

https://clan8blog.wordpress.com/2014/06/26/removing-a-parameter-from-psboundparameters/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/162)*

**Comment by tysonjhayes** [comment]
Reviewed 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/162)*

**Comment by eshaparmar** [comment]
@nzspambot are you still planning to work on this? or can we close this pr?

**Comment by johlju** [comment]
As this is part of an open issue, I will reopen this I leave it as abandoned so someone else can continue the work.

**Pull request closed without merging**
