### PR TITLE
Adding unit tests to xIisFeatureDelegation and xIisMimeTypeMapping (Fixes #181)

### LINKED ISSUE #181: No unit tests for XIisMimeTypeMapping
Need to create unit tests for this module.

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/200)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Couple of small notes. otherwise this looks good to me.

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 76 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi02xTP6bqSkrqPmk9:-KNi02xTP6bqSkrqPmkA:-1604948866) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L76)):*
> ```PowerShell
>                          -Metadata 'overrideMode' `
>                          -Value $OverrideMode
>                           
> ```

Are we adding white space here? I always get confused with reviewable on this.

---

*[Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1, line 168 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi0Vm556YBUmBe3mh7:-KNi0Vm6NLP9n40qLlk-:1355602849) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1#L168)):*
> ```PowerShell
>     #endregion
> 
> }
> ```

Looks like you need a line break here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-:-KNi0_llnvKTFqNI0XV6:977311966)*

**Comment by mbreakey3** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 76 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi02xTP6bqSkrqPmk9:-KNiKLlQZQwpd88OS3EW:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L76)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Are we adding white space here? I always get confused with reviewable on this.
</details>
Done.

---

*[Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1, line 168 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi0Vm556YBUmBe3mh7:-KNiKMGaTsQzaTa3OMMg:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1#L168)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Looks like you need a line break here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/200)*

**Comment by mbreakey3** [comment]
Review status: 2 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1, line 168 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi0Vm556YBUmBe3mh7:-KNiKQk5jRfZ0GLE378y:1297732085) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1#L168)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Done.
</details>
Huh... I don't know what's going on here. I added in another newline, but it doesn't seem to have changed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/200)*

**Comment by tysonjhayes** [comment]
I consider this good so once you get the line break fixed I would merge.

---

Reviewed 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1, line 168 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi0Vm556YBUmBe3mh7:-KNiP3JqUeiDI4tytste:1887559001) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1#L168)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Huh... I don't know what's going on here. I added in another newline, but it doesn't seem to have changed
</details>
Strange, does your editor automatically remove it? I would assume not but  ¯\_(ツ)_/¯

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-:-KNiPDug26Li9aSPfddG:-895594992)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/200)*

**Comment by mbreakey3** [comment]
*[Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1, line 168 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/200#-KNi0Vm556YBUmBe3mh7:-KNiQ66Ejxm4MCc-lkJC:2045013879) ([raw file](https://github.com/powershell/xwebadministration/blob/0a7d72e00571637eb00c3046b9dad53d9b770abb/Tests/Unit/MSFT_xIisMimeTypeMapping.tests.ps1#L168)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary>
> Strange, does your editor automatically remove it? I would assume not but  ¯\_(ツ)_/¯
</details>
Found the problem
Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/200)*

**Pull request merged**
