### PR TITLE
Website binding certificate subject compare fails with multiple entries

### LINKED ISSUE #412: xWebsite: Certificate subject compare fails with multiple entries
#### Details of the scenario you tried and the problem that is occurring
Currently working on a scenario to create a certificate signed by our CA and bind it as a website binding to a website.

As long as I use a simple subject like the host name the binding goes correct. As soon as I enter a subject as it is required within our company it fails. I figured out where the problem occurs.

**Example:** 
Subject:
```CN=hostname.domain.net, E=myemail@domain.net, O=My Company., OU=IT, L=Place, S=State, C=Somewhere```

I dug into it further and found where the mismatch happens. I encounterd a similar issue with the certificate request itself.
See issue : https://github.com/PowerShell/CertificateDsc/issues/173
And PR: https://github.com/PowerShell/CertificateDsc/pull/174/

The solution for this case was in short to split,trim and sort the subjects before they are compared. 

When I make a request like the example above and check the subject after the certificate is created it comes back like : 
```E=myemail@domain.net, CN=hostname.domain.net, OU=IT, O=My Company, L=Place, S=State, C=Somewhere```

**Notice the order and the spaces after the commas.** 

So back to the Website binding issue: 
Test-TargetResource
https://github.com/PowerShell/xWebAdministration/blob/85ff094ebbd9522ce5b6128ba645d164c1eb3704/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L782

Goes to function Test-WebsiteBinding
https://github.com/PowerShell/xWebAdministration/blob/85ff094ebbd9522ce5b6128ba645d164c1eb3704/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1905

Goes to function ConvertTo-WebBinding
https://github.com/PowerShell/xWebAdministration/blob/85ff094ebbd9522ce5b6128ba645d164c1eb3704/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1248

Goes to function Find-Certificate
https://github.com/PowerShell/xWebAdministration/blob/85ff094ebbd9522ce5b6128ba645d164c1eb3704/DSCResources/Helper.psm1#L101

The subject compares with a simple @('($_.Subject -eq $Subject)') this fails when the order is not correct and the spaces are in the certificate. 
https://github.com/PowerShell/xWebAdministration/blob/85ff094ebbd9522ce5b6128ba645d164c1eb3704/DSCResources/Helper.psm1#L166

I updated the subject's certfilter with something like: 
```$certFilters += @('(@(Compare-Object -ReferenceObject (($_.Subject -split ", ").trim()|sort-object) -DifferenceObject (($subject -split ",").trim()|sort-object)| Where-Object -Property SideIndicator -eq "=>").Count -eq 0)')```

And tested it a few times and that seems to work.

I try to make a pull request to solve this (first timer) 

#### Verbose logs showing the problem
**Error:** 
Failed to execute Test-TargetResource functionality with error message: Desired website bindings are not valid for website "MyWebsite"

#### Suggested solution to the issue
I think about one of these solutions
1) Update the subject's certfilter with something like: 
https://github.com/PowerShell/xWebAdministration/blob/85ff094ebbd9522ce5b6128ba645d164c1eb3704/DSCResources/Helper.psm1#L166

```$certFilters += @('(@(Compare-Object -ReferenceObject (($_.Subject -split ", ").trim()|sort-object) -DifferenceObject (($subject -split ",").trim()|sort-object)| Where-Object -Property SideIndicator -eq "=>").Count -eq 0)')```

I tested the above and this works, also a split etc is done in other filters.

2) Use the compare subject function created in https://github.com/PowerShell/CertificateDsc/pull/174/
And maybe move it to the CertificateDSC.Common instead of inside the MSFT_CertReq/MSFT_CertReq.psm1

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
Windows 2012

```powershell
# insert configuration here
```

### PR DESCRIPTION
**Pull request by wh33ly**
#### Pull Request (PR) description
Website binding certificate subject compare fails with multiple entries
As described in the issue, this will fix an issue where the binding needs the correct certificate. Search for the certificate failed when a subject contains more then one property and the order differs from the original subject.

#### This Pull Request (PR) fixes the following issues
- Fixes #412
#### Task list
- [X] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [X] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Comment-based help added/updated.
- [ ] Examples appropriately added/updated.
- [X] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/413)

### CODE REVIEW

**Comment by wh33ly** [comment]
I could use some help to make the tests better not sure where I need to change what to get it working. 

I would like to test the **xWebsite resource** within the binding info the **certificatesubject** like
```CertificateSubject    = 'CN=contoso, E=myemail@contoso.com, O=Organization, OU=IT, DC=com, L=Location, S=State, C=Country'```

**Comment by regedit32** [comment]
@wh33ly Thanks for submitting a fix for this issue.  Just small feedback provided and I think it'll be ready.

**Comment by wh33ly** [comment]
@regedit32  Think I'm done, is there anything from my side I need to do now ?

**Comment by wh33ly** [comment]
@regedit32 Bump

**Comment by regedit32** [comment]
@wh33ly Sorry for the delay, let me take a look today.

**Pull request merged**
