### PR TITLE
[#325] Added ServerAutoStart to xWebsite

### PR DESCRIPTION
**Pull request by bozho**
Added ServerAutoStart setting to xWebsite, which controls the website autostart flag.

Updated documentation for ServiceAutoStartEnabled, which controls
application auto-initialization.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/339)

### CODE REVIEW

**Comment by bozho** [comment]
Hm, how do I debug failing appveyor tests?

**Comment by johlju** [comment]
@bozho there are suggestion that issue #314 have a solution to the failing tests. Someone need to implement it to see if it works. Would be extremely grateful if someone solved this.

**Comment by johlju** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://beta.reviewable.io/reviews/powershell/xwebadministration/339#-LAmMjqNB6ORx8ho999u:-LAmMjqNB6ORx8ho999v:b-e0ymw2) (no related file):*
Could we add an example that shows a website with ServerAutoStart?

---

*[a discussion](https://beta.reviewable.io/reviews/powershell/xwebadministration/339#-LAmMwEKCREpLpHsKwrC:-LAmMwEKCREpLpHsKwrD:bs93rxc) (no related file):*
Can you please add a test that tests this new property ServerAutoStart?

---

*[README.md, line 243 at r1](https://beta.reviewable.io/reviews/powershell/xwebadministration/339#-LAmL2i546TEcrJImyOd:-LAmL2i546TEcrJImyOe:b-fsfcrp) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/README.md#L243)):*
> ```Markdown
> 
> ### Unreleased
> ```

Please remove extra blank line

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 35 at r1](https://beta.reviewable.io/reviews/powershell/xwebadministration/339#-LAmMMTb5NRvYz5sRBYl:-LAmMMTb5NRvYz5sRBYm:bawc059) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L35)):*
> ```
>     [Write] String DefaultPage[];
>     [Write] String EnabledProtocols;
>     [Write, Description ("Enables autostart for a Website.")] Boolean ServerAutoStart;
> ```

Can we use the same description as in the README.md?

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 37 at r1](https://beta.reviewable.io/reviews/powershell/xwebadministration/339#-LAmMaDJ-CaicJR11bOK:-LAmMaDJ-CaicJR11bOL:bk1fg2i) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L37)):*
> ```
>     [Write, Description ("Enables autostart for a Website.")] Boolean ServerAutoStart;
>     [write, EmbeddedInstance("MSFT_xWebAuthenticationInformation"), Description("Hashtable containing authentication information (Anonymous, Basic, Digest, Windows)")] String AuthenticationInfo;
>     [Write, Description ("Allows the application to automatically initialize without a request")] Boolean PreloadEnabled;
> ```

We should update this in the README.md as well.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 38 at r1](https://beta.reviewable.io/reviews/powershell/xwebadministration/339#-LAmM_nS32a1rIBPdIPX:-LAmM_nS32a1rIBPdIPY:bawc059) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L38)):*
> ```
>     [write, EmbeddedInstance("MSFT_xWebAuthenticationInformation"), Description("Hashtable containing authentication information (Anonymous, Basic, Digest, Windows)")] String AuthenticationInfo;
>     [Write, Description ("Allows the application to automatically initialize without a request")] Boolean PreloadEnabled;
>     [Write, Description ("Enables application autostart.")] Boolean ServiceAutoStartEnabled;
> ```

Can we use the same description as in the README.md?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xwebadministration/339)*

**Comment by bozho** [comment]
Review status: 3 of 10 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/339#-LAmMjqNB6ORx8ho999u:-LB0Aumm0NWQ9Edz4wnp:b32wtd) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could we add an example that shows a website with ServerAutoStart?
</blockquote></details>

ok

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/339#-LAmMwEKCREpLpHsKwrC:-LB0KYt82aaxAhLPnJWK:b-pfpzfw) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can you please add a test that tests this new property ServerAutoStart?
</blockquote></details>

I've added both integration and unit tests, I hope they'll do.

---

*[README.md, line 243 at r1](https://reviewable.io/reviews/powershell/xwebadministration/339#-LAmL2i546TEcrJImyOd:-LB0B6vDEX4A92ngPHUE:b32wtd) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/README.md#L243)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Please remove extra blank line
</blockquote></details>

ok

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 35 at r1](https://reviewable.io/reviews/powershell/xwebadministration/339#-LAmMMTb5NRvYz5sRBYl:-LB0Biya6A2aU_MBxwNW:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L35)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we use the same description as in the README.md?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 37 at r1](https://reviewable.io/reviews/powershell/xwebadministration/339#-LAmMaDJ-CaicJR11bOK:-LB0Bt3LAwZBn8Pdpuw5:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should update this in the README.md as well.
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 38 at r1](https://reviewable.io/reviews/powershell/xwebadministration/339#-LAmM_nS32a1rIBPdIPX:-LB0C7p3--MsTHkAe7V_:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/493b8a4d02496ed0ef4ca7e1989a6128f38d7930/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L38)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we use the same description as in the README.md?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/339)*

**Comment by johlju** [comment]
:lgtm:

@bozho Awesome work! Although, I can't merge this until PR #335 has been merged first (fixes tests failing). Once that is merged you will have to rebase, and then all tests should pass! I ping you when PR #335 has been merged.

---

Reviewed 7 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/339#-:-LB1lnop1IjTCABjXu7l:b-1zr690)*

**Comment by johlju** [comment]
Closing an reopening this to kick off the tests since PR  #335 was merged.

**Comment by johlju** [comment]
@bozho Could you please resolve the failing test. These test are failing because of this change I believe. 

https://ci.appveyor.com/project/PowerShell/xwebadministration/build/1.17.1019.0#L4188

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by gaelcolas** [comment]
@bozho any chance you can pick this up and fix the conflict/test failing so I can merge it?
Tag me and I'll remove the Abandoned label.

Thanks!

**Comment by bozho** [comment]
@johlju Let's revive this PR :)

**Comment by johlju** [comment]
Trying to continue the review on this one, but having issue with Reviewable on this PR. I submitted an issue for that to see if it can be resolved.

**Comment by johlju** [comment]
@bozho This is ready to be merged, I'm just working on the https://github.com/Reviewable/Reviewable/issues/676 to see if there is an edge case issue with Reviewable that could be solved. If they can use this PR to found a bug, let's keep it open for a few more days before merging. See the issue for more information.

**Comment by bozho** [comment]
@johlju Sure, no rush.

**Comment by bozho** [comment]
@johlju I've reformatted the code, but noticed that `MSFT_xWebsite.config.ps1` has inconsistent closing braces for arrays of hashtables. In some cases, `})` is used, and in some cases, `)` is on the next line.

I like the latter approach better.

**Comment by johlju** [comment]
I lake the latter approach too. I can't see you pushed any changes yet. 🙂

**Comment by bozho** [comment]
Just wanted to check about the braces, will push in a moment :)

**Comment by johlju** [comment]
@gaelcolas Can you merge in this PR?

**Comment by gaelcolas** [comment]
Is it me or I don't see an entry in the changeling?

**Comment by johlju** [comment]
The change log is in the README.md file. It should be split up as other repos, but that’s for another PR. In the beginning all repos had then in the README.md.

**Pull request merged**
