### PR TITLE
Added support for website without physical path setting

### PR DESCRIPTION
**Pull request by hansmelin**
See issue https://github.com/PowerShell/xWebAdministration/issues/264 and original feature https://github.com/PowerShell/xWebAdministration/pull/91

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/265)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 169 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXr5_4lORxty144cijW:-KXr5_4lORxty144cijX:bhax5ak) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L169)):*
> ```PowerShell
>         .SYNOPSYS
>         The Set-TargetResource cmdlet is used to create, delete or configure a website on the 
>         target machine.
> ```

can you add a comment about this change here in the help comment for this function?

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXr5vzd5EKNcWjtPNHu:-KXr5vzd5EKNcWjtPNHv:b2o42s4) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
> ```PowerShell
>             if ([String]::IsNullOrEmpty($PhysicalPath)) {
>                 # If no physical path is provided set a default since it is required by New-WebSite if not in force mode
>                 $PhysicalPath = "C:\NonExistent"
> ```

This change needs to be added to the Unreleased section of the README.md as well.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 886 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXr5oO0ZWVOnevrghU3:-KXr5oO1PIEO0YZY7esI:b-vrb03b) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L886)):*
> ```PowerShell
>                 $MockParameters.PhysicalPath = ''
> 
>                 Set-TargetResource @MockParameters
> ```

this line should be inside the 'It'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by mbreakey3** [comment]
Thank you for opening a PR for this issue! Most of the changes look great, just a few minor things.

**Comment by hansmelin** [comment]
*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXtnlA8cR-FePcbJXdq:-KXtnlA8cR-FePcbJXdr:b-9c14zu) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
> ```PowerShell
>             if ([String]::IsNullOrEmpty($PhysicalPath)) {
>                 # If no physical path is provided set a default since it is required by New-WebSite if not in force mode
>                 $PhysicalPath = "C:\NonExistent"
> ```

I can see now that the physical path must point at an existing path in New-Website in order to work. The test method does not validate this. So "C:\NonExistent" won't work.

I can not see any other way than leave out -PhysicalPath and  run New-Website in force mode.

What do you think @mbreakey3?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by mbreakey3** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXtnlA8cR-FePcbJXdq:-KXvAA1HCHl06R-YSd2D:b-kwef28) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
<details><summary><i>Previously, hansmelin (Hans Melin) wrote…</i></summary><blockquote>

I can see now that the physical path must point at an existing path in New-Website in order to work. The test method does not validate this. So "C:\NonExistent" won't work.

I can not see any other way than leave out -PhysicalPath and  run New-Website in force mode.

What do you think @mbreakey3?
</blockquote></details>

Yeah, it looks like this fix would require a larger change. @travisez13 - Do you have an opinion on how to handle this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by TravisEz13** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXtnlA8cR-FePcbJXdq:-KXwfVoTewTMGUbBb8qO:b-dl56xd) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

Yeah, it looks like this fix would require a larger change. @travisez13 - Do you have an opinion on how to handle this?
</blockquote></details>

Have we defined what the possible values of `PhysicalPath` provided to the resource mean?

Example: 
- null or not specified  -  Does this mean which of the following?
     1. The resource will ensure that the `PhysicalPath` is not set, even if the site already exists.
     1. The resource will just create the site without the path.  If the site already exists, the resource will not make any changes to the `PhysicalPath`.
- empty string - I think this should be the same as null or not specified (but  we should consider this case.)


To me, `ii` is the better option.

If you want to ensure that the PhysicalPath is removed, we need to have another property to specify that behavior ( I don't think it's required unless someone asks for it.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by hansmelin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXtnlA8cR-FePcbJXdq:-KXu_BsaSQ24Cpu_qhhP:bjkn8a1) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary><blockquote>

Have we defined what the possible values of `PhysicalPath` provided to the resource mean?

Example: 
- null or not specified  -  Does this mean which of the following?
     1. The resource will ensure that the `PhysicalPath` is not set, even if the site already exists.
     1. The resource will just create the site without the path.  If the site already exists, the resource will not make any changes to the `PhysicalPath`.
- empty string - I think this should be the same as null or not specified (but  we should consider this case.)


To me, `ii` is the better option.

If you want to ensure that the PhysicalPath is removed, we need to have another property to specify that behavior ( I don't think it's required unless someone asks for it.)
</blockquote></details>

I agree on option `ii`. This is the desired behavior if  `PhysicalPath` is null or empty. But this also means that we must call New-Website with the `-Force` flag

But if `PhysicalPath` is set we should not call New-Website with the `-Force` flag since we still want to validate that the path exists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by hansmelin** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXtnlA8cR-FePcbJXdq:-KXyqyLQ1g92X0ifFeJc:borhz1v) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
<details><summary><i>Previously, hansmelin (Hans Melin) wrote…</i></summary><blockquote>

I agree on option `ii`. This is the desired behavior if  `PhysicalPath` is null or empty. But this also means that we must call New-Website with the `-Force` flag

But if `PhysicalPath` is set we should not call New-Website with the `-Force` flag since we still want to validate that the path exists.
</blockquote></details>

I have now make a new commit with the desired behavior. Please,  @mbreakey3 and @travisez13 have a look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by TravisEz13** [comment]
Have you signed the CLA per @msftclas ?

Tab characters are still in the files.  See test results.

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-:-KY-u-NlUEE70ZFcXo1k:b-3nzehp)*

**Comment by hansmelin** [comment]
The tabs has been removed. I have signed the CLA and has got a confirmation mail that it was approved by the CLA admin.

---

Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-:-KYD8G-OTOH9DChcGqai:brlgfp)*

**Comment by hansmelin** [comment]
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 169 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXr5_4lORxty144cijW:-KYNFHoi63vziy6AWKd1:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L169)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

can you add a comment about this change here in the help comment for this function?
</blockquote></details>

Done.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 500 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXr5vzd5EKNcWjtPNHu:-KYNFGFm2ZoR7_cuFkLb:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L500)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

This change needs to be added to the Unreleased section of the README.md as well.
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 886 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-KXr5oO0ZWVOnevrghU3:-KYNF7YeD-sY5pQB0_RE:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/fb456d9ab9f4173b3cd5fb922f2fcf7a657db47a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L886)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

this line should be inside the 'It'
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265)*

**Comment by TravisEz13** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-:-KYPjVjz4NniiyN-pLIR:bnfp4nl)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2, 2 of 2 files at r3.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/265#-:-KYQ7nvH5C1tgkZ1qv6A:bnfp4nl)*

**Pull request merged**
