### PR TITLE
xWebsite: multiple HTTPS bindings with different thumbprints (#332)

### LINKED ISSUE #332: BUG in SSL certificates assignment to bindings
Repro:
```PowerShell
$BindingInfo = @(
    New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
        Protocol              = 'https'
        IPAddress             = '*'
        Port                  = 443
        HostName              = 'api.bittitan.com'
        CertificateThumbprint = '34AE59F4CFA28602716C46D172850747B36624D8'
        CertificateStoreName  = 'WebHosting'
        SslFlags              = 1
    } -ClientOnly
    New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
        Protocol              = 'https'
        IPAddress             = '*'
        Port                  = 443
        HostName              = '*.migrationwiz.com'
        CertificateThumbprint = 'DE0A409C2F2BF8DF47C9154EDE3C3309CAB9E0F7'
        CertificateStoreName  = 'WebHosting'
        SslFlags              = 1
    } -ClientOnly
)

Update-WebsiteBinding -Name MigrationWiz -BindingInfo $BindingInfo
```
Despite different CertificateThumbprint specified for the first and second binding BOTH get the same (first) certificate assigned!

### PR DESCRIPTION
**Pull request by mcbobke**
#### Pull Request (PR) description
Fix multiple HTTPS bindings on one xWebsite receiving the first binding's certificate, added unit regression test and changelog entry. Credit to @konste for the original fix #347 

#### This Pull Request (PR) fixes the following issues
- Fixes #332 
- Closes #347 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/437)

### CODE REVIEW

**Comment by mcbobke** [comment]
@johlju please let me know if there are more tests to be written or if you have any other guidance.

**Comment by johlju** [comment]
I will review this as soon as I can. But had to work late a the day job today. I will try to get to it tomorrow or Saturday.

**Comment by mcbobke** [comment]
Thank you for the update and for taking the time to review it, I understand being busy!

**Comment by johlju** [comment]
No problem, happy to get this resolved. :slightly_smiling_face: 

@mcbobke (or @gaelcolas) Could you please add `Closing #347` to the PR description, then that PR will close also when this is merged.

@gaelcolas can you please merge this one? (poking Gael offline to)

**Comment by mcbobke** [comment]
Added Closes #347.

**Comment by johlju** [comment]
@mcbobke got myself permission to this repo so I can merge myself now.

**Comment by mcbobke** [comment]
Awesome! Thank you!

**Pull request merged**
