### PR TITLE
BREAKING CHANGE: Update xIisFeatureDelegation to manage all sections

### LINKED ISSUE #358: xIisFeatureDelegation should support any path instead of hard-coding /system.webServer
Currently xIisFeatureDelegation has a hardcoded Set-WebConfiguration `-Filter "/system.webServer/$SectionName"` which limits the ability to unlock sections under any other path like '/system.web'.  I propose we make the filter more dynamic so an admin can specify any path.  This would be a breaking change if we do not create a new resource for this.

Another addition could be to update the resource to support managing this at the server level or site level.  Currently the resource only supports this at the server level.  This can be managed by adding an optional parameter for `PsPath` and default to 'machine/webroot/apphost' if not specifed.

### PR DESCRIPTION
**Pull request by regedit32**
Updated xIisFeatureDelegation to support managing any IIS configuration section instead of paths relative to /system.webserver (hard-coded).  Also allows specifying IIS path to apply at site or server level.  This is a breaking change as parameters have changed and one was added.

Fixes #358

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome job with the code! Thanks for fixing style issues!

---

Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 235 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaly9H76PGCpxPKitL:-LDaly9H76PGCpxPKitM:bwrbmnq) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L235)):*
> ```Markdown
> * **Ensure**: Ensures if the bindings are **Present** or **Absent**.
> 
> ### xIisFeatureDelegation
> ```

Would you mind adding a description of this resource, what the resource is used for? 

---

*[README.md, line 238 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaoss6DLbZw2O7zc3M:-LDaoss6DLbZw2O7zc3N:b-dvvdv7) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L238)):*
> ```Markdown
> 
> * **Filter**: Specifies the IIS configuration section to lock or unlock in this format: **/system.webserver/security/authentication/anonymousAuthentication**
> * **Path**: Specifies the configuration path. This can be either an IIS configuration path in the format computer machine/webroot/apphost, or the IIS module path in this format IIS:\sites\Default Web Site.
> ```

Question (my lack of knowledge): Is it possible to use the both path's in a configuration to end up setting the same value for a property? Thinking if there could be a ping-pong behavior? Or does both path set's entirely different properties?

---

*[README.md, line 269 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDamZZN7p50IclQCgY4:-LDamZZO2D4tIx-EBR4p:b-4o3osb) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L269)):*
> ```
> Breaking Change:
> ```

Please write this in all upper case.

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 9 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDanDxwA_QgcocR6MH4:-LDanDxwA_QgcocR6MH5:b-lchrcm) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L9)):*
> ```
> GetOverrideMode
> ```

This doesn't seem to be used in the changed code.

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 80 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaqtHG0qe28lUKPc46:-LDaqtHG0qe28lUKPc47:bbltzx0) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L80)):*
> ```PowerShell
> function Set-TargetResource
> {
>     [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSUseShouldProcessForStateChangingFunctions", "")]
> ```

Non-blocking: Not part of your code, but would you mind removing this? We should not have this here. 

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 100 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaqOJOCA9Asb-CkRrY:-LDaqOJOCA9Asb-CkRrZ:bo2nt2q) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L100)):*
> ```
> ( $($LocalizedData.VerboseSetTargetResource) -f $Filter, $OverrideMode )
> ```

Non-blocking (throughout): Should be enough writing this as (skipping `$()`).

``` 
( $LocalizedData.VerboseSetTargetResource -f $Filter, $OverrideMode )
```

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 102 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDao12aDNQv1L_ZPg7-:-LDao12aDNQv1L_ZPg70:b-q527kf) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L102)):*
> ```
> $PsPath
> ```

Should be `$Path` I think? We should make sure the unit test can catch this, I think it didn't catch this because `Assert-MockCalled` is not using `-ParameterFilter`to check so it was called with the correct parameters. 

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 122 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDar6Sq6WJVVKhXhOC0:-LDar6Sq6WJVVKhXhOC1:bbltzx0) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L122)):*
> ```PowerShell
> function Test-TargetResource
> {
>     [Diagnostics.CodeAnalysis.SuppressMessageAttribute("PSDSCUseVerboseMessageInDSCResource", "")]
> ```

Non-blocking: Not part of your code, but would you mind removing this? We should not have this here. 

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 161 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaq4Sj6VEhF0EeHGt0:-LDaq4Sj6VEhF0EeHGt1:bjhvgsb) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L161)):*
> ```
> PsPath
> ```

Should be Path?

---

*[DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1, line 184 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDan6Nk4UtjTBbnifiC:-LDan6Nk4UtjTBbnifiD:b-73ndom) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/DSCResources/MSFT_xIisFeatureDelegation/MSFT_xIisFeatureDelegation.psm1#L184)):*
> ```
> ChangedMessage
> ```

Maybe this should be GetOverrideMode?

---

*[Examples/Sample_xIisFeatureDelegation_AllowSome.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDatZkiAKWZBY-OCffH:-LDatZkiAKWZBY-OCffI:bbgixun) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Examples/Sample_xIisFeatureDelegation_AllowSome.ps1#L1)):*
> ```
> configuration Sample_IISFeatureDelegation
> ```

We should change this to `configuration Example`. This way the example can be tested correctly (when resource module is ready to opt-in for those tests).

---

*[Examples/Sample_xIisFeatureDelegation_AllowSome.ps1, line 1 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDatqKWCTh_fxibqmyW:-LDatV7s5Vz91jWOPxxT:beptcjq) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Examples/Sample_xIisFeatureDelegation_AllowSome.ps1#L1)):*
> ```PowerShell
> configuration Sample_IISFeatureDelegation
> ```

We should add a comment-based help on top of this file containing `.SYNOPSIS` with a short description what this example shows.

---

*[Examples/Sample_xIisFeatureDelegation_AllowSome.ps1, line 12 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaskLk8M0KLt3w_4eW:-LDaskLk8M0KLt3w_4eX:b8grx3j) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Examples/Sample_xIisFeatureDelegation_AllowSome.ps1#L12)):*
> ```
> PSDesiredStateConfiguration
> ```

We should change this to PSDscResources

---

*[Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1, line 62 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDawRldACK9OipDyOe6:-LDawRldACK9OipDyOe7:be3hopl) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1#L62)):*
> ```PowerShell
> 
>             It 'Should be able to call Get-DscConfiguration without throwing' {
>                 { Get-DscConfiguration -Verbose -ErrorAction Stop } | Should Not throw
> ```

We should test so the correct hash table is returned here. See example here; https://github.com/PowerShell/SqlServerDsc/blob/f9ff10b67d116392cf6e7820a8f75ade4d436efd/Tests/Integration/MSFT_SqlServerDatabaseMail.Integration.Tests.ps1#L81-L105

I will try to update the integration test template i DscResources today or tomorrow (issue https://github.com/PowerShell/DscResources/issues/328). 

---

*[Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1, line 66 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDayL0k-F5XaJO3VyCs:-LDayL0k-F5XaJO3VyCt:baj7cyv) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1#L66)):*
> ```
> $True
> ```

$true (lower-case 't'). Throughout.

---

*[Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1, line 95 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDayTsb87CLEWfQJzoG:-LDayTsb87CLEWfQJzoH:b-cxfbnl) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Integration/MSFT_xIISFeatureDelegation.Integration.Tests.ps1#L95)):*
> ```PowerShell
> 
>             It 'Should be able to call Get-DscConfiguration without throwing' {
>                 { Get-DscConfiguration -Verbose -ErrorAction Stop } | Should Not throw
> ```

Same as previous comment.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1, line 113 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDazf_I3-LIFOsvLso2:-LDazf_I3-LIFOsvLso3:b4lr514) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1#L113)):*
> ```
> Mock Set-WebConfiguration
> ```

We should use named arguments `Mock -CommandName Set-WebConfiguration`. Throughout.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1, line 118 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDazGFoC9bfO12vfFgW:-LDazGFoC9bfO12vfFgX:bowqucj) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1#L118)):*
> ```PowerShell
> 
>                 It 'Should call all the mocks' {
>                     Assert-MockCalled Set-WebConfiguration -Exactly 1
> ```

We should use parameter filter here so that we know that the mock was called with the right parameters (fyi, the mock does not need parameter filters for this, just the `Assert-MockCalled`). 

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1, line 118 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDazMOH3zFByfiWl_bU:-LDazMOH3zFByfiWl_bV:be9ncln) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1#L118)):*
> ```
> -Exactly 1
> ```

`-Exactly -Times 1`. Throughout. 

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1, line 136 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDas14rDZ_KtZuK1Z5C:-LDas14rDZ_KtZuK1Z5D:bcg3yxg) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1#L136)):*
> ```
> 'OverrideMode is invalid'
> ```

We should add `When...` to the Context blocks (only the ones you changing, but wouldn't mind you doing all). Throughout.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1, line 151 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDasFGiDVHi8Y8NLZAT:-LDasFGiDVHi8Y8NLZAU:bat0el7) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/Tests/Unit/MSFT_xIISFeatureDelegation.Tests.ps1#L151)):*
> ```PowerShell
>             }
> 
>             Context 'OverrideMode is valid' {
> ```

Could we do a test that checks Deny too?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359#-:-LDancihESzN-yrMeCWJ:bcojz9f)*

**Comment by johlju** [comment]
Looks good, just a outstanding question, if it possible to solve that. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 238 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaoss6DLbZw2O7zc3M:-LDk2Z4N34HjnpqUOLed:b8t00s9) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L238)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

Yes, it would be possible to create conflicting resource settings if someone specified `Path = "MACHINE/WEBROOT/APPHOST/Default Web Site"` and`Path = "IIS:\Sites\Default Web Site"` for the same setting(s).  Those resolve to the same path and the LCM would not see it as a conflicting resource.
</blockquote></details>

Would it work to only allow either? Or will that hinder some functionality that cannot be set by either path? 
Looking if we can remove a potential ping-pong behavior if a user mistakenly adds different paths that sets the same property, for example in partial configurations.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359#-:-LDk5F8dCVQrgmaTPGCM:b-n7bj9p)*

**Comment by regedit32** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 238 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaoss6DLbZw2O7zc3M:-LDl3p-s9UnZBbpl7qGD:b-3nqcyh) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L238)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Would it work to only allow either? Or will that hinder some functionality that cannot be set by either path? 
Looking if we can remove a potential ping-pong behavior if a user mistakenly adds different paths that sets the same property, for example in partial configurations.
</blockquote></details>

This scenario could be mitigated by having two separate resources, one to manage Feature Delegation at the site level and one at the server level.  The only difference would be that one would not have a `Path` parameter that defaults to `MACHINE/WEBROOT/APPHOST` to apply at server level and the other would have a `Path` parameter that would be appended in the resource like this `MACHINE/WEBROOT/APPHOST/$Path` to target a website.  

However, I feel like it would be redundant to have two mostly identical resources.  I can't think of any limitations to only being able to use one format or the other, they are both viable path formats for the cmdlets.  I think the scenario of an organization creating two conflicting resource settings by specifying the same path in two different formats would be unlikely, but I guess anything is possible.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359)*

**Comment by johlju** [comment]
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDuH5Fm8iDcGlnIP1gg:-LDuH5Fn3GfS6tjkRvUi:b-jbrfrw) (no related file):*
Could we add add another example file for using `Path = "MACHINE/WEBROOT/APPHOST/Default Web Site"`? 

---

*[README.md, line 238 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaoss6DLbZw2O7zc3M:-LDuECBc0iF8wfCE5Ia3:bse85rc) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L238)):*
<details><summary><i>Previously, regedit32 (Reggie Gibson) wrote…</i></summary><blockquote>

This scenario could be mitigated by having two separate resources, one to manage Feature Delegation at the site level and one at the server level.  The only difference would be that one would not have a `Path` parameter that defaults to `MACHINE/WEBROOT/APPHOST` to apply at server level and the other would have a `Path` parameter that would be appended in the resource like this `MACHINE/WEBROOT/APPHOST/$Path` to target a website.  

However, I feel like it would be redundant to have two mostly identical resources.  I can't think of any limitations to only being able to use one format or the other, they are both viable path formats for the cmdlets.  I think the scenario of an organization creating two conflicting resource settings by specifying the same path in two different formats would be unlikely, but I guess anything is possible.
</blockquote></details>

I rather have one resource too. What I was after if we could prevent the below configuration. But since the only way to do that is to have the resource throw if for example 'IIS:' is used as path. That seems wrong. 

**So can we add a comment here in the documentation to remind the user that both path can be set the same future delegation and there are no way to control if two resources in the configuration set the same future delegation?**


```
xIisFeatureDelegation resource1
{
    Filter       = '<some filter>'
    OverrideMode = 'Allow'
    Path         = 'MACHINE/WEBROOT/APPHOST/Default Web Site'
}

xIisFeatureDelegation resource2
{
    Filter       = '<some filter>'
    OverrideMode = 'Allow'
    Path         = 'IIS:\Sites\Default Web Site'
}
```

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359)*

**Comment by regedit32** [comment]
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDuH5Fm8iDcGlnIP1gg:-LED4eNpEp0kORFMEiWT:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could we add add another example file for using `Path = "MACHINE/WEBROOT/APPHOST/Default Web Site"`? 
</blockquote></details>

Done.

---

*[README.md, line 238 at r2](https://reviewable.io/reviews/powershell/xwebadministration/359#-LDaoss6DLbZw2O7zc3M:-LED4hXh5lWMwxFM8Hg1:b-xla9j0) ([raw file](https://github.com/powershell/xwebadministration/blob/6e97f3fbe94cb638906c818a0932ca2890c5ed0f/README.md#L238)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

I rather have one resource too. What I was after if we could prevent the below configuration. But since the only way to do that is to have the resource throw if for example 'IIS:' is used as path. That seems wrong. 

**So can we add a comment here in the documentation to remind the user that both path can be set the same future delegation and there are no way to control if two resources in the configuration set the same future delegation?**


```
xIisFeatureDelegation resource1
{
    Filter       = '<some filter>'
    OverrideMode = 'Allow'
    Path         = 'MACHINE/WEBROOT/APPHOST/Default Web Site'
}

xIisFeatureDelegation resource2
{
    Filter       = '<some filter>'
    OverrideMode = 'Allow'
    Path         = 'IIS:\Sites\Default Web Site'
}
```
</blockquote></details>

Updated readme with a warning for path types.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359)*

**Comment by johlju** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/359#-:-LEDcR7J5KOpBYzyh6yv:bnfp4nl)*

**Pull request merged**
