### PR TITLE
Fixes: Get-IisHandler : The parameter "Name" is declared in parameter-set "__AllParameterSets" multiple times.

### PR DESCRIPTION
**Pull request by NikCharlebois**
#### Pull Request (PR) description
Fixes an Error where dynamically calling the Get-TargetResource always throws the following error from Get-IISHandler

#### This Pull Request (PR) fixes the following issues
N/A

#### Task list
- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/438)

### CODE REVIEW

**Comment by johlju** [comment]
The style guideline says we should have `[Parameter()]` on variables. Could you fix it by renaming the parameters (and add an regression unit test) that tests so the issue does not regress. 🙂

**Comment by NikCharlebois** [comment]
@johlju can you elaborate on what you actually want me to rename. Thanks

**Comment by johlju** [comment]
Sure! I will review it better tomorrow. :smile:

**Comment by NikCharlebois** [comment]
@johlju It throws the same error. Here is a bogus test I created. Run it for yourself.

function Get-IisHandler
{
    <#
    .NOTES
        Get a list on IIS handlers
    #>
    [CmdletBinding()]
    param
    (
        [Parameter(Mandatory = $true)]
        [ValidateNotNullOrEmpty()]

        [Parameter()]
        [String] $HandlerName,

        [Parameter()]
        [String] $SiteName
    )

    return ""
}

Get-IISHandler -HandlerName "Trace" -SiteName "Blob"

**Comment by johlju** [comment]
@NikCharlebois Sorry my bad! I did not realize the `Parameter()` was specified twice!

**Comment by johlju** [comment]
@NikCharlebois I saw the same problem is in the `Remove-IisHandler` function, would you mind resolving that to in this PR?

**Comment by NikCharlebois** [comment]
Fixed in Remove-IISHandler as well. Thanks

**Pull request merged**
