### PR TITLE
xWebAdministration: Alphabetized the resources in README.md

### LINKED ISSUE #449: Reorder resources alphabetically in README.md
In the README.md the resources are not in alphabetical order, so it's harder to find a resource. We should move these in alphabetical order.

### PR DESCRIPTION
**Pull request by midacts**
Fixes #449

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/502)

### CODE REVIEW

**Comment by midacts** [comment]
Looks better this time.   : )

**Comment by midacts** [comment]
abc...wxyz
"w" comes before "x"?
Or you'd just put it in pretending it has an "x" in front?

**Comment by johlju** [comment]
@midacts Ah sorry, my bad! I just assumed everyone had 'x' in front of them, I didn't read closely 🙂 Thank you for correcting me! 😃

**Comment by midacts** [comment]
Mission complete.

**Comment by midacts** [comment]
Thanks for your help on this and opening these up for me to contribute for Hacktoberfest.

**Comment by johlju** [comment]
@midacts Thank you contributing! 😃

**Pull request merged**
