### PR TITLE
Changed PhysicalPath to be optional in xWebSite

### PR DESCRIPTION
**Pull request by BrianFarnhill**
This change is to allow PhysicalPath to be an optional parameter in xWebSite. The reasoning for this is if you have a website that is provisioned externally to xWebSite (my specific scenario is the Central Administration website in SharePoint) where I do not know the physical path (its unique per deployment) that I need to configure bindings for. By making the physical path optional I can still get my bindings updated to do SSL certificates, but leave the path alone. I added an error trap that makes sure that you add the path where it finds a site that doesn't exist as well to ensure that it continues to function to create new sites correctly while accommodating this scenario for SharePoint as well.

### CODE REVIEW

**Comment by BrianFarnhill** [comment]
Not sure why but the last test run there looks like it [got stuck halfway through](https://ci.appveyor.com/project/PowerShell/xwebadministration/build/1.9.265.0)? You can see the test output of that same change set ID on [my AppVeyor tenant](https://ci.appveyor.com/project/BrianFarnhill/xwebadministration/build/1.9.5.0) though to see they are all passing. Perhaps manually launching the tests again might help them show properly?

**Comment by TravisEz13** [comment]
triggered the PR to rebuild.

**Comment by BrianFarnhill** [comment]
Thanks @TravisEz13 - tests passed this time!

**Comment by tysonjhayes** [comment]
Merged, thanks!

**Comment by hansmelin** [comment]
What has happened with this feature? I can see that now is PhysicalPath required again.

**Comment by BrianFarnhill** [comment]
@hansmelin Where are you seeing that? Looking at the [current schema](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L28) it still looks like its optional

**Comment by hansmelin** [comment]
@BrianFarnhill Yes it is optional in the schema, but it does not work if you leave it out. 
If you look into the code you will find:

            if ([String]::IsNullOrEmpty($PhysicalPath)) {
                throw 'The PhysicalPath Parameter must be provided for a website to be created'
            }

**Comment by BrianFarnhill** [comment]
@hansmelin This was by design in this PR as it was required before hand, the scenario was to make it optional for scenarios where a site would be created elsewhere (in my example, by SharePoint - so I would never know the path at design time) but everything else would be exactly as it was. Looking at the details for the New-Website command we can see that PhysicalPath is still optional there, so in theory this could be done. I suggest adding a new issue to this repo asking for this to be done, and then either look at making the change and contributing it yourself, or wait for one of the other contributors to be able to pick it up as well.

@tysonjhayes Your thoughts on this one?

**Comment by mbreakey3** [comment]
@BrianFarnhill  - Tyson is out until January, but I agree - @hansmelin Go ahead and open a new issue and feel free to open a PR with the fix or wait for someone else to pick it up (though that may be awhile)

**Comment by BrianFarnhill** [comment]
Thanks @mbreakey3 !

**Pull request merged**
