### PR TITLE
Fixed #260 changed LogTruncateSize validation for xIisLogging and xWebsite.

### LINKED ISSUE #260: LogTruncateSize validation issue
It appears that validation on the xIisLogging resource's LogTruncateSize parameter is being handled incorrectly.  The parameter (and its accompanying validation) is typed as a string.  Consequently, the value `536,870,912` (passed as an int, but coerced into a string) fails validation as it is outside the range `'1,048,576'` to `'4,294,967,295'`.  This is clearly not the case, were the values being handled as integers as they should be.  Handled as strings, the leading `5` is indeed bigger than the `1` to `4` that the range specifies.

### PR DESCRIPTION
**Pull request by remcoeissing**
Changed the validation for LogTruncateSize for **xIisLogging** and **xWebsite**. This resolves #260. Opted not to change the MOF Schema, since this would be a breaking change.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/261)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xIISLogging.tests.ps1, line 553 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/261#-KX83uoK4gALFfDRqq0l:-KX83uoK4gALFfDRqq0m:bn49dya) ([raw file](https://github.com/powershell/xwebadministration/blob/488eece8b95b9c9bb324b39e14c28174f51e66fa/Tests/Unit/MSFT_xIISLogging.tests.ps1#L553)):*
> ```PowerShell
>                 Mock -CommandName Set-WebConfigurationProperty
>                 
>                 $result = Set-TargetResource @MockLogParameters
> ```

Set-TargetResource shouldn't be returning a value. 

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 1286 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/261#-KX848RKiJtqSpO6zPf5:-KX848RKiJtqSpO6zPf6:b-jr4ehi) ([raw file](https://github.com/powershell/xwebadministration/blob/488eece8b95b9c9bb324b39e14c28174f51e66fa/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1286)):*
> ```PowerShell
>                     -MockWith { return $MockLogOutput.logExtFileFlags }
> 
>                 $result = Set-TargetResource -Ensure $MockParameters.Ensure `
> ```

Set-TargetResource shouldn't be returning anything.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/261)*

**Comment by mbreakey3** [comment]
Reviewed 3 of 5 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/261)*

**Comment by remcoeissing** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[Tests/Unit/MSFT_xIISLogging.tests.ps1, line 553 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/261#-KX83uoK4gALFfDRqq0l:-KXX7o_zkC4yz3egH8d0:b4keptj) ([raw file](https://github.com/powershell/xwebadministration/blob/488eece8b95b9c9bb324b39e14c28174f51e66fa/Tests/Unit/MSFT_xIISLogging.tests.ps1#L553)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Set-TargetResource shouldn't be returning a value. 
</details>
Done. Cleaned up some more in the unit test.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 1286 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/261#-KX848RKiJtqSpO6zPf5:-KXX9AjPFLhnVUeUrMrG:b5fvkbo) ([raw file](https://github.com/powershell/xwebadministration/blob/488eece8b95b9c9bb324b39e14c28174f51e66fa/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1286)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Set-TargetResource shouldn't be returning anything.
</details>
Done. Cleaned up a bit more unit tests.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/261)*

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/261)*

**Pull request merged**
