### PR TITLE
RTA: xSSLSettings Integration tests & fixes

### PR DESCRIPTION
**Pull request by nzspambot**
Hi, added some basic xSSLSettings integration tests as well as some fixes to xSSLSettings and unit test

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/137)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I'll review this one tomorrow night - run out of time tonight. Sorry about that.

**Comment by tysonjhayes** [comment]
Reviewed 2 of 6 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
Review status: 5 of 7 files reviewed at latest revision, 6 unresolved discussions.

---

*[DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1, line 28 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/137#-KJqyVsUPNkOk1MpJU8U:-KJqyVsUPNkOk1MpJU8V:1906601764) ([raw file](https://github.com/powershell/xwebadministration/blob/ef7d70386ae1c6c16580b4a91b5c79aadd3b5442/DSCResources/MSFT_xSSLSettings/MSFT_xSSLSettings.psm1#L28)):*
> ```PowerShell
>         [AllowEmptyString()]
>         [ValidateSet('','Ssl','SslNegotiateCert','SslRequireCert','Ssl128')]
>         [string[]] $Bindings = ''
> ```

So if it's mandatory why are we giving it a default parameter? To me it's more one or the other.

---

*[Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/137#-KJqyuuUKnty4twUWEFW:-KJqyuuUKnty4twUWEFX:576109485) ([raw file](https://github.com/powershell/xwebadministration/blob/ef7d70386ae1c6c16580b4a91b5c79aadd3b5442/Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1#L5)):*
> ```PowerShell
> 
> #region HEADER
> [String] $moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

I think there is supposed to be a version number in the header now to show which version we're woring with.

---

*[Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1, line 27 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/137#-KJqyzrbFBmgn0IUREsY:-KJqyzrbFBmgn0IUREsZ:-461357619) ([raw file](https://github.com/powershell/xwebadministration/blob/ef7d70386ae1c6c16580b4a91b5c79aadd3b5442/Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1#L27)):*
> ```PowerShell
>     . $ConfigFile
> 
>     $null = Backup-WebConfiguration -Name $tempName
> ```

Let's do a backup before we load the config so if there is ever a problem with loading the config the finally block run successfully.

---

*[Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1, line 47 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/137#-KJqzGU2hyyQPg2qwbRI:-KJqzGU2hyyQPg2qwbRJ:-1418555032) ([raw file](https://github.com/powershell/xwebadministration/blob/ef7d70386ae1c6c16580b4a91b5c79aadd3b5442/Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1#L47)):*
> ```PowerShell
>     # Create a new website for the SSLSettings
> 
>     New-Website -Name $DSCConfig.AllNodes.Website `
> ```

Would it make sense to wrap all of this up into a params hashtable? Might look nicer.

---

*[Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1, line 48 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/137#-KJqz8BINJYl3kzCKEd3:-KJqz8BINJYl3kzCKEd4:1753841138) ([raw file](https://github.com/powershell/xwebadministration/blob/ef7d70386ae1c6c16580b4a91b5c79aadd3b5442/Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1#L48)):*
> ```PowerShell
> 
>     New-Website -Name $DSCConfig.AllNodes.Website `
>         -Id 200 `
> ```

Do we need to specify an ID? In theory someone could have this ID already in use which would cause an issue.

---

*[Tests/Unit/MSFT_xSSLSettings.Tests.ps1, line 31 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/137#-KJqztTW7Gtw3eoTV_C1:-KJqztTW7Gtw3eoTV_C2:2077160083) ([raw file](https://github.com/powershell/xwebadministration/blob/ef7d70386ae1c6c16580b4a91b5c79aadd3b5442/Tests/Unit/MSFT_xSSLSettings.Tests.ps1#L31)):*
> ```PowerShell
>                 Mock Get-TargetResource -Verifiable {return @{
>                     Name = 'Test'
>                     Bindings = @('Ssl')
> ```

Curious why we are changing this?  Seems kind of unncessary, and I only ever see it as SSL not Ssl.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/137)*

**Comment by tysonjhayes** [comment]
Reviewed 2 of 6 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/137)*

**Comment by tysonjhayes** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/137)*

**Pull request merged**
