### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by hahndorf**
The AuthenticationInfo parameter needs to be an 'array' of strings, otherwise using it fails with `Convert property 'AuthenticationInfo' value from type 'STRING' to type 'INSTANCE' failed`. See http://serverfault.com/questions/788733/how-to-use-authenticationinfo-in-xwebapplication-dsc-resource/788921#788921

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/178)

### CODE REVIEW

**Comment by hahndorf** [comment]
So with my changes the tests fail, but in a real life example using `AuthenticationInfo` only works after my changes. Are the tests wrong? Do I do something wrong?

**Comment by mbreakey3** [comment]
It looks like you only updated the .mof file and not the .psm1 file

**Comment by mbreakey3** [comment]
Did you check out the errors that came up for the build?

**Comment by hahndorf** [comment]
I tried to fix someone's problem on serverfault.com but it turned out my fix was completely incorrect. So I will delete this pull request.

**Pull request closed without merging**
