### PR TITLE
Removed "Create and Configure application pool" examples.

### PR DESCRIPTION
**Pull request by Abijith10**
Removed "Create and Configure Application Pool" Examples.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/492)

### CODE REVIEW

**Comment by johlju** [comment]
@Abijith10 Thank you for your contribution. Can you please send in this PR again and please base your branch on the dev branch. When sending in a PR make sure it targets the dev branch (should be default)

I will close this PR with the invalid label at this time.

**Comment by Abijith10** [comment]
What did I do wrong here?

**Comment by Abijith10** [comment]
I would be happy to correct it.

**Comment by Abijith10** [comment]
Got it!

**Pull request closed without merging**
