### PR TITLE
added required modules

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/104)

### CODE REVIEW

**Comment by KarolKaczmarek** [comment]
*[xWebAdministration.psd1, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/104#-KE7zwxHdP61nzLPVx0p:-KE7zwxIls72K-d4DM5Y:-191403202) ([raw file](https://github.com/powershell/xwebadministration/blob/fa79e7344e2734cda675e8ab6a7af0eaf2275d0b/xWebAdministration.psd1#L28)):*
Should we be requiring the modules which are only required by examples? This will have cascading effect and user will end up downloading dozens of modules he doesn't really need just because examples require them. 
We should perhaps discuss with the ScriptAnalyzer team if there's a better way to solve those PSSA errors. 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xwebadministration/104)*

**Comment by KarolKaczmarek** [comment]
@mbreakey3 There are some tests failures, can you work on resolving those? https://ci.appveyor.com/project/PowerShell/xwebadministration/build/1.9.290.0

**Comment by tysonjhayes** [comment]
Yeah I don't think we should make xPhp and xMySql requirements for the module. For example most of my use cases do not involve either one of these being used.  I'm not even really sure I want to take a dependancy on xPSDesiredStateConfiguration as again it doesn't actually give me anything related to managing my webservers and now I have to have it present everywhere just to be able to load this module.

I would rather remove the examples then take this dependancy personally (and I honestly don't really want to remove the examples either).

**Comment by mbreakey3** [comment]
Is there a way that the examples could be written so that they don't need dependent modules?

**Comment by tysonjhayes** [comment]
@mbreakey3 Probably, but there are some I think are better with the dependancies as it shows a fuller scope of how it all ties together.  Could you help me understand the goal of this so I can better help scope the fixes?

**Comment by mbreakey3** [comment]
That makes sense. We're working on figuring out a better a solution. Right now the issue is that the examples have dependencies that the main resource scripts do not. Since they're in the same module, though, they use the same .psd1 file which includes all dependent modules.

**Comment by TravisEz13** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[xWebAdministration.psd1, line 28 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/104#-KE7zwxHdP61nzLPVx0p:-KErsX2d3gUDTsxF1M2D:676269983) ([raw file](https://github.com/powershell/xwebadministration/blob/fa79e7344e2734cda675e8ab6a7af0eaf2275d0b/xWebAdministration.psd1#L28)):*
:+1:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/104)*

**Comment by TravisEz13** [comment]
They aren't really in the same module.  They are just files along for the ride with the module.  So they should not make the module dependent.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/104#-:-KEscow2nhbXbWYO_Lcc:-1723868628)*

**Comment by KarolKaczmarek** [comment]
Closing this since after internal discussions we decided not to follow this approach.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/104#-:-KFG0i-FZX-VFrXEzcH9:2003486613)*

**Pull request closed without merging**
