### PR TITLE
Added examples and updated Readme.md (Fixes #207)

### LINKED ISSUE #207: README.md missing info on resources
Currently information on these resources is not included in the readme file:
-xIisFeatureDelegation
-xIisHandler
-xIisMimeTypeMapping
-xWebAppPoolDefaults
-xWebSiteDefaults

### PR DESCRIPTION
**Pull request by remcoeissing**
On top of the associated issues it should also fix #207, which is a duplicate of #191.

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/248)

### CODE REVIEW

**Comment by eshaparmar** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/248#-:-KXMb27wW78DgGsSbIxV:bnfp4nl)*

**Comment by mbreakey3** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[Tests/Integration/MSFT_xWebConfigKeyValue.config.ps1, line 41 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/248#-KXgBQ24F8usEW3c3MJC:-KXgBQ24F8usEW3c3MJD:bfheads) ([raw file](https://github.com/powershell/xwebadministration/blob/5f5e6e4a8c0647fab151d47f82c6bc59acf50894/Tests/Integration/MSFT_xWebConfigKeyValue.config.ps1#L41)):*
> ```PowerShell
>         WebsitePath     = $env:xWebConfigKeyValuePsPath
>     }
> }
> ```

Needs a newline at the end here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/248)*

**Comment by remcoeissing** [comment]
Review status: 6 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[Tests/Integration/MSFT_xWebConfigKeyValue.config.ps1, line 41 at r1](https://reviewable.io:443/reviews/powershell/xwebadministration/248#-KXgBQ24F8usEW3c3MJC:-KXgrghZszZSXJk7rJyI:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/5f5e6e4a8c0647fab151d47f82c6bc59acf50894/Tests/Integration/MSFT_xWebConfigKeyValue.config.ps1#L41)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

Needs a newline at the end here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/248)*

**Comment by tysonjhayes** [comment]
Closing this as I have a new PR to fix it.

**Pull request closed without merging**
