### PR TITLE
Update CHANGELOG.md

### LINKED ISSUE #446: Move change log from README.md to CHANGELOG.md
We should move the change log out from the README.md and into a separate file CHANGELOG.md.

See example https://github.com/PowerShell/ActiveDirectoryDsc/blob/dev/CHANGELOG.md

Also in the README.md we should add a change log section. See example https://github.com/PowerShell/ActiveDirectoryDsc#change-log

### PR DESCRIPTION
**Pull request by devevignesh**
## Pull Request (PR) description

Update CHANGELOG.md described in #446

#### This Pull Request (PR) fixes the following issues
Fixes #446

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/480)

### CODE REVIEW

**Comment by johlju** [comment]
@devevignesh I need this change merged, so hope you din't mind, I will try to resolve the review comments myself. Other PR's starting to get in that needs this change (other wise we need to rebase this one for every new PR).

**Comment by devevignesh** [comment]
@johlju Hey that's fine. Is there anything else I need to fix?

**Comment by johlju** [comment]
Something strange happened with the CI pipeline. Closing and directly reopening this PR.

**Comment by johlju** [comment]
@devevignesh I don't think so. I looks good. Just need the CI pass then I merge.

**Comment by johlju** [comment]
Closing and directly reopening this PR to kick off the CI pipeline again. It is acting very strange for some reason. Typical when I want it to be quick. 😆

**Comment by johlju** [comment]
@devevignesh Thank you for fixing this! 🙇

**Pull request merged**
