### PR TITLE
Added missing resources to readme

### PR DESCRIPTION
**Pull request by hahndorf**
added missing information about xIisFeatureDelegation, xIisMimeTypeMapping and xWebAppPoolDefaults to readme.md

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/237)

### CODE REVIEW

**Comment by mbreakey3** [comment]
The build got hung, I re-built it and it should be fine since you only updated the readme.

**Comment by hahndorf** [comment]
The Appveyor build hung twice already, and now we are getting a error in a test I have not changed. I'm not sure what to do now. I don't use these tools often enough to fully understand them.

**Comment by mbreakey3** [comment]
@hahndorf - Yes, I understand your frustration. I'll look into this issue. It looks like it might be have something to do with changes that were recently added to our common tests.

**Comment by mbreakey3** [comment]
Rebuilding the PR, I think we found the issue.

**Comment by mbreakey3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 145 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlq7RKi14yfSrV2s44:-KSlq7RLwzu9DR-wIYxW:b-ehxy2v) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L145)):*
> ```Markdown
>         * **2**: The secure connection be made using the Centralized Certificate Store without requiring a Server Name Indication.
>         * **3**: The secure connection be made using the Centralized Certificate Store while requiring Server Name Indication.
> * **ApplicationPool**: The website�s application pool.
> ```

These quotes got messed up somehow when you were making your changes. Could you go in and manually change them back? Sometimes this happens depending on the text editor you're using.

---

*[README.md, line 168 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqLtFKbY8kWu3I-Ij:-KSlqLtFKbY8kWu3I-Ik:b-jy3gwr) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L168)):*
> ```Markdown
> * **Website**: Name of website with which the web application is associated.
> * **Name**: The desired name of the web application.
> * **WebAppPool**:  Web application�s application pool.
> ```

Same with this one.

---

*[README.md, line 202 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqQXbRbJOTXlwzBVa:-KSlqQXbRbJOTXlwzBVb:bs3cctt) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L202)):*
> ```Markdown
> 
> ### xIisFeatureDelegation
> * **SectionName**: relative path of the section to delegate such as **security/authentication**
> ```

Relative

---

*[README.md, line 213 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqhocLxPRY8PnET3A:-KSlqhocLxPRY8PnET3B:b-qilqwa) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L213)):*
> ```Markdown
> * **ApplyTo**: Required Key value, always **Machine**
> * **ManagedRuntimeVersion**: CLR Version {v2.0|v4.0|} empty string for unmanaged.
> * **ApplicationPoolIdentity**: {ApplicationPoolIdentity | LocalService |LocalSystem | NetworkService}
> ```

space between | and LocalSystem

---

*[README.md, line 567 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqm2cAwcUpYBM52uq:-KSlqm2cAwcUpYBM52ur:bkvyzir) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L567)):*
> ```Markdown
> ### Create a new website
> 
> While setting up IIS and stopping the default website is interesting, it isn�t quite useful yet.
> ```

Another quote issue

---

*[README.md, line 662 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqp6YfDMoM8BEGStM:-KSlqp6YfDMoM8BEGStN:b5si2b) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L662)):*
> ```Markdown
> ### Creating the default website using configuration data
> 
> In this example, we�ve moved the parameters used to generate the website into a configuration data file.
> ```

another quote issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/237)*

**Comment by hahndorf** [comment]
Thanks for your help Mariah, in my initial commit I did noticed the incorrect quotes and fixed them, but then to trigger another appveyor build I made one small change in the wrong Markdown editor. I will fix them and try again.

**Comment by mbreakey3** [comment]
No problem, the bug with the AppVeyor build was on our end, so I apologize for the difficulty in getting this change merged in. Thank you for your patience!

**Comment by mbreakey3** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 145 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlq7RKi14yfSrV2s44:-KSltWW_IReDDwmpY9i6:b32w0x) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L145)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> These quotes got messed up somehow when you were making your changes. Could you go in and manually change them back? Sometimes this happens depending on the text editor you're using.
</details>
OK

---

*[README.md, line 168 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqLtFKbY8kWu3I-Ij:-KSltX_AAQWfYBfqs7TW:b32w0x) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L168)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Same with this one.
</details>
OK

---

*[README.md, line 567 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqm2cAwcUpYBM52uq:-KSlt_3V-hb0t5LUveKv:b32w0x) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L567)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Another quote issue
</details>
OK

---

*[README.md, line 662 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqp6YfDMoM8BEGStM:-KSlta05B-6UV43Z2ELK:b32w0x) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L662)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> another quote issue
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/237)*

**Comment by hahndorf** [comment]
Now I lost track, were the broken quotes messages from before or after my last commit? Do I have to do something?

**Comment by mbreakey3** [comment]
Broken quotes are all fixed, now there's just 2 more minor style fixes needed.

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[README.md, line 202 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqQXbRbJOTXlwzBVa:-KSm9N9STCWWg4yEB-LQ:b32w0x) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L202)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Relative
</details>
OK

---

*[README.md, line 213 at r3](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-KSlqhocLxPRY8PnET3A:-KSm9OBp3nw6SKAgINX-:b32w0x) ([raw file](https://github.com/powershell/xwebadministration/blob/c8a4a2104a4098d377677ebd703155f3248092bf/README.md#L213)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> space between | and LocalSystem
</details>
OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/237#-:-KSm9QotOqJYhO_JY8zQ:bnfp4nl)*

**Pull request merged**
