### PR TITLE
Update to fix Write-Verbose errors

### PR DESCRIPTION
**Pull request by mansong1**
Fixes for the following errors:

**_A parameter cannot be found that matches parameter name 'f'_** 
The formatted string for the Message parameter of Write-Verbose was not enclosed in parentheses.

**_A positional parameter cannot be found that accepts argument 'S'_**
Not sure why there is an S, but removing it fixed the error.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/240)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@mbreakey3 Can you look at the test failures here? They don't seem to be related to this PR, and they look similar to ones you were looking at before/

**Comment by mbreakey3** [comment]
This needs to be merged into 'dev' not 'master'

**Comment by mbreakey3** [comment]
That should fix the build error. Also, make sure you [rebase](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts) from dev.

**Comment by kwirkykat** [comment]
@mansong1 @mbreakey3 I was able to update the base branch from this end. Tests all passing now. :lgtm: 

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/240#-:-KUy0W3BQi9mpxt8PnES:b2qzs02)*

**Pull request merged**
