### PR TITLE
Add Integer value support to xWebConfigProperty (fixes #374)

### LINKED ISSUE #374: xWebConfigProperty: Return the wrong type for some values
This is from PR https://github.com/PowerShell/xWebAdministration/pull/330 review comment, it was commented on line 137 in MSFT_xWebConfigProperty.psm1 

```
Set-WebConfigurationProperty `
            -Filter $Filter `
            -PSPath $WebsitePath `
            -Name $PropertyName `
....
```

Some configuration property values are strings and some are integers, but we can only have one datatype for $value in the mof. We should add a helper function to convert it to integer if needed. Something like this, but perhaps there is a better way:

```
$checkvalue = Get-WebConfigurationProperty -PSPath $WebsitePath -Filter $Filter -Name $PropertyName

if ($checkvalue -isnot [System.String])
{
    $propertyType = $value.TypeName
}

if ($propertyType -eq "system.int64")
{
    [int]$value = [convert]::ToInt64($value, 10)
} 
```
For example, this filter"system.webServer/security/requestFiltering/requestLimits" and this property maxAllowedContentLength, has a integer value.

On second thought, my example assumes that the property exists. If the property is $null then Get-WebConfigurationProperty wouldn't be able to return a TypeName. However, with the same filterGet-WebConfiguration can, even if the property is null. This would apply to the WebConfigPropertyCollection as well.

### PR DESCRIPTION
**Pull request by regedit32**
Update to xWebConfigProperty so it can manage web configuration properties that are integer data types. This will check the attribute schema for the specified property to determine which data type to convert the string value to.(Fixes #374)

I didn't update the readme because this is a change to an unreleased resource, so not sure if it made sense to add anything there.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/376)

### CODE REVIEW

**Comment by johlju** [comment]
Awesome work on this!  This looks good, so clean code, only two nit-picks (that I hesitated to even comment on).

Thank you so much for fixing the outstanding issue from the previous PR (and resolving the style in the tests!)! 

---

Reviewed 2 of 4 files at r1, 2 of 2 files at r2.
Review status: all files reviewed, 2 unresolved discussions (waiting on @regedit32)

---

*[DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1, line 302 at r2](https://reviewable.io/reviews/powershell/xwebadministration/376#-LG0Wk_P1nG2w8dz4tET:-LG0U_RvBdqx0SRxS6gY:b-qu42f3) ([raw file](https://github.com/powershell/xwebadministration/blob/fb3f19d07e467278450cfed4445c9454440f4140/DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1#L302)):*
> ```PowerShell
> 
> <#
> .SYNOPSIS
> ```

We should indent this one one step (like you did with the other).

---

*[Tests/Unit/MSFT_xWebConfigProperty.tests.ps1, line 183 at r2](https://reviewable.io/reviews/powershell/xwebadministration/376#-LG0Wnr22tl6tU0N9gNn:-LG0Wnr22tl6tU0N9gNo:brxzocx) ([raw file](https://github.com/powershell/xwebadministration/blob/fb3f19d07e467278450cfed4445c9454440f4140/Tests/Unit/MSFT_xWebConfigProperty.tests.ps1#L183)):*
> ```
> -MockWith {}
> ```

We could remove this from the mock when no code is being mocked. Throughout.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/376#-:-LG0W_c13mI_9ssl7eCC:b-sl7f09)*

**Comment by regedit32** [comment]
thanks Johan!

---

Review status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @johlju)

---

*[DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1, line 302 at r2](https://reviewable.io/reviews/powershell/xwebadministration/376#-LG0Wk_P1nG2w8dz4tET:-LG2x4jx7_5Ix2q1eLNG:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/fb3f19d07e467278450cfed4445c9454440f4140/DSCResources/MSFT_xWebConfigProperty/MSFT_xWebConfigProperty.psm1#L302)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We should indent this one one step (like you did with the other).
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWebConfigProperty.tests.ps1, line 183 at r2](https://reviewable.io/reviews/powershell/xwebadministration/376#-LG0Wnr22tl6tU0N9gNn:-LG2x7cTAIfn7EhmoZRb:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/fb3f19d07e467278450cfed4445c9454440f4140/Tests/Unit/MSFT_xWebConfigProperty.tests.ps1#L183)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> -MockWith {}
> ```

We could remove this from the mock when no code is being mocked. Throughout.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/376#-:-LG2xAXuBRq848Q4QS-L:b-34j3j1)*

**Comment by johlju** [comment]
@regedit32 I usually close and reopen the PR, that kicks off the tests again.

**Comment by johlju** [comment]
@regedit32 would it help adding a `Start-Sleep` before `Restore-WebConfiguration` and wait a few seconds for it to release the lock? Or should we just re-try a few times with a few seconds interval until an error is thrown?

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/376#-:-LG4TmGRDDONWXGfOXkf:bnfp4nl)*

**Pull request merged**
