### PR TITLE
Fix webapp backslash naming issue

### PR DESCRIPTION
**Pull request by gigi81**
Fix for an error when creating web apps that have a backslash in the
name. The backslash is replaced automatically with a forward slash.

To reproduce the error try to create a web app with a name like "test\app"
On the first dsc run the web app is created correctly.
From the second run forward the following error is returned:

Job {0B17F381-0877-11E6-80C7-005056B835FE} : 
MIResult: 1
Error Message: Destination element already exists, please use "force" parameter to override.
Message ID: Destination element already exists, please use "force" parameter to override.,Microsoft.IIs.PowerShell.Provider.NewWebApplicationCommand
Error Category: 5
Error Code: 5
Error Type: MI

This is due to the fact that the name is actually 'test/app' after it's created so Get-WebApplication fails to find the web app.

$webApplication = Get-WebApplication -Name "test\app"
# $webApplication is $null

$webApplication = Get-WebApplication -Name "test/app"
# $webApplication is populated

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/118)

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Howdy, can you fix any of the conflicts and resubmit this?

**Comment by tysonjhayes** [comment]
Hi, are you able to fix the merge conflicts?

**Comment by gigi81** [comment]
Hi,
I'm still waiting for my boss to get back to me on the cla.
I don't understand what is exactly the merge issue for such a trivial change. I will just create a new branch with the change and have another pull request once I have an ok on the cla.

**Comment by gigi81** [comment]
It looks on now!

**Comment by tysonjhayes** [comment]
Howdy, looks like we're still waiting on you to sign the CLA. Is that something you think you are going to be able to do?

**Comment by gigi81** [comment]
Hi,
I had to ask my boss, who asked his boss, who asked the head of IT... next one is the CTO but I don't think we will need to get there...
So short answer is hopefully in a few more days...

**Comment by tysonjhayes** [comment]
@TechIsCool - I've got to wait for @gigi81 to sign the CLA before I can merge. :|

**Comment by tysonjhayes** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/118)*

**Comment by TechIsCool** [comment]
@gigi81 Are you going to be able to sign the CLA? Just figured I would check in since this bug blocking a puppet deploy of mine.

**Comment by gigi81** [comment]
Hi guys, sorry for the delay but I'm still waiting for an ok. Unfortunately within big companies this things take time. I cannot give you a precise timeline but I hope it will be a matter of days now.

**Comment by gigi81** [comment]
My company authorized me to sign the CLA, so I just signed it and uploaded through docusign.
@tysonjhayes  I think you can now merge the PR.

**Comment by TechIsCool** [comment]
@gigi81 Congrats thanks for the update. Hope to see this merged soon.

**Comment by mbreakey3** [comment]
@gigi81 Great! Can you fix the merge conflicts?

**Comment by gigi81** [comment]
Hi @mbreakey3 I merged the dev branch. Anyway the build seems to be stuck

**Comment by mbreakey3** [comment]
Yep, looks like it was stuck. I just re-built it. Hopefully it'll work this time

**Comment by mbreakey3** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/118#-:-KMAR_SIoJNtfIMzMsNi:1417088721)*

**Comment by gigi81** [comment]
seems good. can we merge it?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/118#-:-KMONNwuIR_s5HLZEICp:-909449339)*

**Comment by mbreakey3** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/118)*

**Pull request merged**
