### PR TITLE
RTA: xWebApplication Integration tests & fixes

### PR DESCRIPTION
**Pull request by nzspambot**
Hi, added some basic xWebApplication integration tests as well as some fixes to xWebApplication

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/136)

### CODE REVIEW

**Comment by PlagueHO** [comment]
I'll give this a review tomorrow night unless someone else gets to it first. I'll also take a look at the AppVeyor issue.

**Comment by tysonjhayes** [comment]
Unfortunately neither @PlagueHO or I have rights to rerun it. Easiest way is to add a line break somewhere and checkin which kicks off another build (terrible I know) or page @KarolKaczmarek or @TravisEz13 and ask nicely. :grin:

**Comment by PlagueHO** [comment]
Reviewed 4 of 5 files at r1, 2 of 3 files at r3, 2 of 2 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[README.md, line 192 \[r5\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KIoOtA9esv4o24DPYCe:-KIoOtA9esv4o24DPYCf:104234857) ([raw file](https://github.com/powershell/xwebadministration/blob/aa518ff42146a16cfc98de455292ba7afb02e2e5/README.md#L192)):*
> ```Markdown
> * Adding conditional logic to install the test helper module from the gallery if the user downloaded the module from the gallery.
> * Added **xWebApplication** integration tests
> * Added fixes to **xWebApplication**
> ```

Can we mention what the fixes to xWebApplication were? New SSL Flags added etc

---

*[DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof, line 0 \[r5\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KIoSd9nruAsJVQM6NkC:-KIoSd9nruAsJVQM6NkD:66634203) ([raw file](https://github.com/powershell/xwebadministration/blob/aa518ff42146a16cfc98de455292ba7afb02e2e5/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof#L0)):*
There appears to be a problem with the MSFT_xSSLSettings.schema.mof
Both Reviewable and GitHub are reporting this file is a binary file (so the content is not being shown for review). Can you check it please? Might need to recreate it or check the char encoding etc.

---

*[Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1, line 4 \[r5\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KIoT-pOA9B5GJguQX7I:-KIoT-pOA9B5GJguQX7J:-530933099) ([raw file](https://github.com/powershell/xwebadministration/blob/aa518ff42146a16cfc98de455292ba7afb02e2e5/Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1#L4)):*
> ```PowerShell
> $Global:DSCResourceName = 'MSFT_xWebApplication'
> 
> #region HEADER
> ```

Could you update the header here or add the version number? 

Nice work on all of this - especially the integration tests too. Nice to see such complete coverage, I think everyone should be trying to achieve this level (including myself)! :smile:

---

*[Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1, line 4 \[r5\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KIoUEVhvJTDQfVNl3d4:-KIoUEVhvJTDQfVNl3d5:681548921) ([raw file](https://github.com/powershell/xwebadministration/blob/aa518ff42146a16cfc98de455292ba7afb02e2e5/Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1#L4)):*
> ```PowerShell
> $Global:DSCResourceName    = 'MSFT_xWebAppPoolDefaults'
> 
> # Integration Test Template Version: 1.1.0
> ```

Can you add the #region HEADER above this line (just so the #Region collapse still works).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by PlagueHO** [comment]
That is actually a pretty good idea. If we do this perhaps we do it to the template one and advise it to be changed for all AppVeyor.yml (I've run into the same thing in lots of other projects). Perhaps we could use xWebAdministration as the test project for this change - @tysonjhayes?

Anyway, @tysonjhayes, this :LGTM: so ready for merge.

<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> hmm appveyor failed _yet_ again
> 
> 
> 
> ```
> 
> Exception calling "UploadFile" with "2" argument(s): "The remote server returned an error: (500) Internal Server Error."
> 
> At line:3 char:97
> 
> + ... /ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", (Res ...
> 
> +                                              ~~~~~~~~~~~~~~~~~~~~
> 
>     + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
> 
>     + FullyQualifiedErrorId : WebException
> 
>  
> 
> Command executed with exception: Exception calling "UploadFile" with "2" argument(s): "The remote server returned an error: (500) Internal Server Error."
> 
> ```
> 
> 
> 
> I reckon this could be wrapped in a try/catch/while loop
> 
> 
> 
> e: https://github.com/appveyor/ci/issues/826 :tumbleweeds:
</details>


---

Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[README.md, line 192 \[r5\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KIoOtA9esv4o24DPYCe:-KIpZtExxbeJVZBNuIME:-2062951561) ([raw file](https://github.com/powershell/xwebadministration/blob/aa518ff42146a16cfc98de455292ba7afb02e2e5/README.md#L192)):*
<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> Done.
</details>
Thanks sir!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-:-KIp_1ulKAoPJTpazp5W:-1794779168)*

**Comment by PlagueHO** [comment]
Review status: 7 of 8 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof, line  \[r5\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KIoSd9nruAsJVQM6NkC:-KIp_X6y4NrW2tHDAkDx:-996119793) ([raw file](https://github.com/powershell/xwebadministration/blob/aa518ff42146a16cfc98de455292ba7afb02e2e5/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.schema.mof#L)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> There appears to be a problem with the MSFT_xSSLSettings.schema.mof
> Both Reviewable and GitHub are reporting this file is a binary file (so the content is not being shown for review). Can you check it please? Might need to recreate it or check the char encoding etc.
</details>
Actually, I still missed this issue. Did you manage to figure out what is wrong with this MOF File?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by PlagueHO** [comment]
There is supposed to be:

https://github.com/PowerShell/DscResource.Tests/blob/dev/Meta.Tests.ps1#L99
https://github.com/PowerShell/DscResource.Tests/blob/dev/MetaFixers.psm1#L67

I wonder if these tests could be updated to fail the file?

**Comment by PlagueHO** [comment]
It should fail - but for some reason in this case it didn't. Needs to be fixed I reckon!

**Comment by TravisEz13** [comment]
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1, line 217 \[r6\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KJ3NwJOtlIQbGv2KX3r:-KJ3NwJOtlIQbGv2KX3s:-1721701241) ([raw file](https://github.com/powershell/xwebadministration/blob/b5aec44d6c09e43a0f47694cb84014bbee9e68a6/DSCResources/MSFT_xWebApplication/MSFT_xWebApplication.psm1#L217)):*
> ```PowerShell
> 				Set-ItemProperty -Path "IIS:\Sites\$Website\$Name" `
> 								 -Name serviceAutoStartEnabled `
> 								 -Value $serviceAutoStartEnabled `
> ```

We should not be replacing spaces with tabs.
see [Style guidelines -general, point 1](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md#general-rules)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by tysonjhayes** [comment]
@nzspambot as annoying as it is I've actually seen bugs with commands auto completing and ruining intended functionallity when a script has tabs in it, vs I do not see this with spaces. So the intent is not to spark a ververant debate but to actually correct for unintentded bugs (imo).

**Comment by PlagueHO** [comment]
I've run into issues with Tabs and PowerShell as well (especially with back ticks).

As I was reading these reviews I was watching the most recent episode of Silicon Valley - with the Spaces vs. Tabs conflict - made me LOL. If you haven't watched it (or watch this show), I highly recommend it.

**Comment by TravisEz13** [comment]
Reviewed 1 of 1 files at r7.
Review status: 7 of 8 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r8.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by tysonjhayes** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1, line 28 \[r8\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KJqw6Fw1aXTpNwxyznO:-KJqw6Fw1aXTpNwxyznP:813958680) ([raw file](https://github.com/powershell/xwebadministration/blob/746532af71fae20fc803dbd021a3f8e8bdfa75a4/Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1#L28)):*
> ```PowerShell
>     . $ConfigFile
> 
>     $null = Backup-WebConfiguration -Name $tempName
> ```

We should move this above loading the config file (basically the firs tthing we do) as it can present some errors in restoring/removing the backup if the config file ever gets horked.

---

*[Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1, line 57 \[r8\]](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-KJqwLZKLqjmJAKJtyMO:-KJqwLZKLqjmJAKJtyMP:626211075) ([raw file](https://github.com/powershell/xwebadministration/blob/746532af71fae20fc803dbd021a3f8e8bdfa75a4/Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1#L57)):*
> ```PowerShell
>     # Create a new website for the WebApplication
> 
>     New-Website -Name $DSCConfig.AllNodes.Website `
> ```

Does it make sense to do this with a params hashtable? Might look a bit cleaner.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by tysonjhayes** [comment]
Reviewed 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Comment by PlagueHO** [comment]
:lgtm:

<details><summary><i>Previously, nzspambot (James Baker) wrote…</i></summary>
> I removed the tabs as requested
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-:-KJx965bqbzUXkAF9SBZ:1417088721)*

**Comment by PlagueHO** [comment]
Oh wait - looks like there is still a merge conflict to resolve. :frowning: 

<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary>
> :lgtm:
</details>


---

Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136#-:-KJx9Mvb0l4eirBzG_Jr:-2024289735)*

**Comment by PlagueHO** [comment]
Reviewed 1 of 1 files at r7, 1 of 1 files at r9.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/136)*

**Pull request merged**
