### PR TITLE
README: 450 toc

### LINKED ISSUE #450: Add a a ToC to the resource section in the README.md
We should add a ToC to the top of the resource section in the README.md, before all the individual resource sections. The Table of Contents should look similar to this example https://github.com/PowerShell/SqlServerDsc#resources. The Table of Contents should be in alphabetical order and have a link to each individual resource section.

This should replace the list at the top a line 3 https://github.com/PowerShell/xWebAdministration/blame/dev/README.md#L3

### PR DESCRIPTION
**Pull request by midacts**
Fixes #450

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/497)

### CODE REVIEW

**Comment by midacts** [comment]
if you let me know what's wrong, i'll fix it for the PR.

looks like appveyor is failing on missing tests?

**Comment by X-Guardian** [comment]
It is failing the `Common Tests - Validate Markdown Files` meta test with multiple errors on the README.md:

```
C:\projects\xwebadministration\README.md: 90: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
C:\projects\xwebadministration\README.md: 91: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
C:\projects\xwebadministration\README.md: 95: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
C:\projects\xwebadministration\README.md: 96: MD004/ul-style Unordered list style [Expected: dash; Actual: asterisk]
etc
```

Don't know why it has suddenly started doing this. I can'r see any upstream changes in DscResource.Tests that will have triggered this, but to fix it, change all the list asterisks to dashes.

Can I also suggest a better title for the PR, such as 'Add a ToC to the resource section in the README.md' so in the future it is easier to see what a PR did, without having to refer to the referenced issue.

**Comment by johlju** [comment]
@midacts Please also update the CHANGELOG.md with an entry explaining this change.

**Comment by midacts** [comment]
#503 - opened this PR instead as i didnt know how to just work from dev.

so i just started fresh from dev.

**Pull request closed without merging**
