### PR TITLE
RTA: xIisRemoteManagement

### PR DESCRIPTION
**Pull request by nzspambot**
Hi

As mentioned here is a IIS RemoteManagement resource with:

1) Unit tests
2) Int tests
3) example
4) updated README

thanks

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/281)

### CODE REVIEW

**Comment by kwirkykat** [comment]
@nzspambot Re-running the tests. Test failure seems out of place for just a README change.

**Comment by kwirkykat** [comment]
@nzspambot Looks like there is a missing newline now (sorry common tests were *just* updated to include .md files).

Then there is a very odd failure further down:
[-] Disabling IISRemoteManagment 1.22s
      Expected: {False}
      But was:  {False}
      at line: 88 in C:\projects\xwebadministration\Tests\Integration\MSFT_xIISRemoteManagement.Integration.Tests.ps1
      88:             $webMgmtService | Should Be 'False'

No idea what's going on there. Maybe an issue with the new version of Pester that was released yesterday?

**Comment by kwirkykat** [comment]
@nzspambot The changes from string --> boolean are correct though. It's an issue with how those tests were originally written. Pester 4 is just more accurate with types apparently than Pester 3.

Could prolly fix the tests pretty easily by just replacing 'False'/'false' with $false and 'True'/'true' with $true in Notepad++ or an IDE. Do you want to do it here or would you like me to open another PR to fix the other tests?

**Comment by kwirkykat** [comment]
@nzspambot Ah. Didn't see those. Yeah all we can do is open an issue for Pester then and see what they say 😕

**Comment by tysonjhayes** [comment]
Reviewed 5 of 7 files at r1, 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1, line 50 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMaV28idGOjpPLhe1D:-KbMaV28idGOjpPLhe1E:b-ss4d16) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1#L50)):*
> ```PowerShell
>     if ((Get-WindowsFeature -Name Web-Server).Installed -ne $true)
>     { 
>         $errorMessage = $LocalizedData.ErrorWebServerStateFailure -f $_.Exception.Message
> ```

Why aren't we just passing this into the parameter instead of assigning to a variable?

---

*[DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1, line 85 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMagxG550BRlZpWn6L:-KbMagxG550BRlZpWn6M:bistgxy) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1#L85)):*
> ```PowerShell
>     }
> 
>     Write-Verbose -Message ($LocalizedData.VerboseGetTargetResult)
> ```

You should put this above the return line.

---

*[DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1, line 126 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMi_eUK-rJKGWpmkF6:-KbMi_eUK-rJKGWpmkF7:bjfar3g) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1#L126)):*
> ```PowerShell
>             Write-Verbose -Message ($LocalizedData.VerboseSetTargetInstallingRemoteManagement)
>             Import-Module -Name $module
>             Install-WindowsFeature -Name $windowsFeature
> ```

This function doesn't work (the function exists but it errors.... How obnoxious.) on clients, and I believe is called IIS-ManagementService. Currently our current code base supports both client and server and I'm not sure I'm willing to break that at this point.

If we wrote a helper function to detect the OS (server or client) we could easily switch which install/uninstall we use to compensate for this.

---

*[DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1, line 136 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMhTNOcb1ElEKLJnMR:-KbMhTNPGudeeMmNtcBx:b-tfroco) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1#L136)):*
> ```PowerShell
>     }
> 
>     if ($getState.State -ne $State)
> ```

I'd flip these to disable the service before uninstalling it. In theory you could run into an instance where you've uninstalled the feature/service before you've attempted to stop it resulting in an error.

---

*[DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1, line 193 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMhIa1yeYwhYNGUsHS:-KbMhIa1yeYwhYNGUsHT:b2569bs) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.psm1#L193)):*
> ```PowerShell
>     {
>         Write-Verbose -Message ($LocalizedData.VerboseTestTargetState)
>         Return $false
> ```

return should be lowercase.

---

*[DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.schema.mof, line 5 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMfdE-1rbjgpznmSBj:-KbMfdE-1rbjgpznmSBk:buckhhx) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/DSCResources/MSFT_xIisRemoteManagement/MSFT_xIisRemoteManagement.schema.mof#L5)):*
> ```
> class MSFT_xIisRemoteManagement : OMI_BaseResource
> {
>     [Key, ValueMap{"Started","Stopped"}, Values{"Started","Stopped"}] String State;
> ```

Could we add descriptions here please? In the future I'd like to use the autodoc which pulls descriptions from here.

---

*[Examples/Sample_xIISRemoteManagement.ps1, line 1 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMmFxW79QgCiPBRx0v:-KbMmFxW79QgCiPBRx0w:b-5h9yz8) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/Examples/Sample_xIISRemoteManagement.ps1#L1)):*
> ```PowerShell
> {
> ```

not sure why we have curly braces here, could we remove these?

Also could you add a synopsis at the top explaining what this is showing (it's obvious I know but if we pull in the auto document writer it uses that info).

---

*[Tests/Integration/MSFT_xIISRemoteManagement.Integration.Tests.ps1, line 51 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMg-R_JOwx40U6TSgF:-KbMg-R_JOwx40U6TSgG:b-m0sdub) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/Tests/Integration/MSFT_xIISRemoteManagement.Integration.Tests.ps1#L51)):*
> ```PowerShell
>             Invoke-Expression -Command "$($script:DSCResourceName)_Enabled -OutputPath `$TestDrive"
>             Start-DscConfiguration -Path $TestDrive -ComputerName localhost -Wait -Verbose -Force
>             
> ```

nit: Could you remove all of the blank spaces from this file please?

---

*[Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1, line 1 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMg6zmVGsTOTcEqDxl:-KbMg6znVq9ANOR477FA:bghmng9) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1#L1)):*
> ```PowerShell
> $global:DSCModuleName = 'xWebAdministration'
> ```

We shouldn't be using global variables. Typically I just redeclare the script variable in the inmodulescope brace to get the writing to work out.

---

*[Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1, line 61 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMi9nACVu6WqiyTNIg:-KbMi9nACVu6WqiyTNIh:b-v40txp) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1#L61)):*
> ```PowerShell
>             }
>         }
>         
> ```

Could you also remove all of the blanks from this file too?

---

*[Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1, line 85 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMgeJ6zhZfjUMujJJR:-KbMgeJ6zhZfjUMujJJS:b-373gx) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1#L85)):*
> ```PowerShell
>                
>                 It -name 'should call Get-WindowsFeature twice' -test {
>                     Assert-MockCalled -CommandName Get-WindowsFeature -Exactly -Times 2
> ```

Why should it be calling this twice? Your code shows it calling it once. One time for get-windowsfeature and one time for get-service.

---

*[Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1, line 129 at r4](https://reviewable.io:443/reviews/powershell/xwebadministration/281#-KbMhnIqi1FduH4vZSet:-KbMhnIqi1FduH4vZSeu:bvct1f5) ([raw file](https://github.com/powershell/xwebadministration/blob/f6a6f5a169a32933903e1fddf25d5287795413ff/Tests/Unit/MSFT_xIISRemoteManagement.tests.ps1#L129)):*
> ```PowerShell
>             }
>             
>             Context -Name 'All Settings are incorrect' -Fixture {
> ```

I'm not sure this test is really needed, it's really hitting the same code path as the next test which is checking the state.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/281)*

**Comment by johlju** [comment]
Reopen this PR as it is part of an open issue. I will label this as abandoned for the time being so someone else can continue to work on this.

**Pull request closed without merging**
