### PR TITLE
Moved example Sample_xWebsite_StopDefault out from README.md

### LINKED ISSUE #486: xWebSite: Move example from README.md to examples folder
This example https://github.com/PowerShell/xWebAdministration#stopping-the-default-website should be moved to the Examples folder. Preferably in the individual resource example folder if it exist.
In the description for the comment-based help it should use the text that describing the example in the README.md.

*Please note that examples are tested so they can be compiled.*

### PR DESCRIPTION
**Pull request by tomlarse**
#### Pull Request (PR) description
Changes described in #486 

#### This Pull Request (PR) fixes the following issues
fixes #486

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/499)

### CODE REVIEW

**Comment by tomlarse** [comment]
should probably implement #483 first?

**Comment by johlju** [comment]
This works, we can implement #483 after this is merged.

**Comment by johlju** [comment]
I will merge PR #500 before this one, I didn't realize you resolved that one too! It's awesome! 😄

**Comment by tomlarse** [comment]
Yeah, I'll update the changelog and move to the right folder structure after #500 is merged. I can take care of #485, #487 and #488 as well then if no one else has taken them.

**Comment by johlju** [comment]
Would be great if you can take care of the other issues as well. 😃 

I will merge PR #500 as soon as the tests pass. There are so many commits pushed so the CI pipeline is behind. :)

**Comment by tomlarse** [comment]
Will do. I'll do the other ones as well. Do you want separate PR's from each, or can I put all of them here?

**Comment by johlju** [comment]
Do as you like. You may put all of them here if you like.

**Comment by tomlarse** [comment]
I think you can just close it now, it seems like the other ones related are already in progress :)

**Comment by johlju** [comment]
Ah okay! I'm having a hard time keeping up with the PRs which one resolves what. :) Then I will review this one. But will be tomorrow, it's late here now.

**Comment by johlju** [comment]
@tomlarse Thank you for this!

**Pull request merged**
