### PR TITLE
Unit test fixes

### PR DESCRIPTION
**Pull request by mbreakey3**
Adding a file of stub functions and making a few fixes to the mocks in the unit tests so that all of the unit tests can be run on a local machine (not just a server) with no outside dependencies.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/180)

### CODE REVIEW

**Comment by mbreakey3** [comment]
@TravisEz13 would you mind reviewing these changes so I can merge?

**Comment by kwirkykat** [comment]
Reviewed 1 of 1 files at r2.
Review status: 1 of 11 files reviewed at latest revision, 8 unresolved discussions.

---

*[WebAministrationStubs.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf3NhHeICpfxJGHAkp:-KMf3NhHeICpfxJGHAkq:-2046500748) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/WebAministrationStubs.psm1#L1)):*
> ```PowerShell
> 
> ```

Mariah will fix the style here later if needed. This file should be renamed MockWebAdministrationWindowsFeature.psm1.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 887 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMeza0UXKpPsHh0GsRD:-KMeza0UXKpPsHh0GsRE:2104999148) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L887)):*
> ```PowerShell
>     }
> } 
> ```

Please add a help comment with a synopsis and description of the parameter.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 897 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf-ADeMoJ3gtQVRnYd:-KMf-ADeMoJ3gtQVRnYe:-769463078) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L897)):*
> ```PowerShell
> 
>     # This is a local preference for the function which will terminate
>     # the program if there's an error invoking appcmd.exe
> ```

Change to a multi-line <# #> comment.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 900 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMezxQA9_GLyvE20Zrx:-KMezxQA9_GLyvE20Zry:-183711818) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L900)):*
> ```PowerShell
>     $ErrorActionPreference = 'Stop'
> 
>     $filePath = "$env:SystemRoot\System32\inetsrv\appcmd.exe"
> ```

Rename variable to appCmdFilePath.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1, line 8 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf04ek01pehLahAa48:-KMf04el6D-PmOLBSPxG:815898500) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1#L8)):*
> ```PowerShell
> 
> [String] $moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> $repoSource = (Get-Module -Name $script:DSCModuleName -ListAvailable)
> ```

Remove [String]. It is not necessary. This should be in the script: scope. $Script:MyInvocation.MyCommand.Path should be removed and $PSScriptRoot should just be used instead to import modules so that the test doesn't rely on where the invocation happens.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1, line 62 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf0u9qSMO8KXE8_Fpn:-KMf0u9rzscgvkjs5Bad:2122662676) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1#L62)):*
> ```PowerShell
> }
> 
> Import-Module (Join-Path -Path $moduleRoot -ChildPath "WebAministrationStubs.psm1")
> ```

Change file name to MockWebAdministrationWindowsFeature.psm1 to make this more clear.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 106 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf2H1r3ZMNFgx2ksW-:-KMf2H1r3ZMNFgx2ksW0:-1281490125) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xWebsite.Tests.ps1#L106)):*
> ```PowerShell
>             }
> 
>             Mock -CommandName Assert-Module {}
> ```

Add -MockWith named parameter.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 1012 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf2aW-6xCsSq2oDQQH:-KMf2aW-6xCsSq2oDQQI:926725635) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1012)):*
> ```PowerShell
>                 Mock -CommandName Get-Website
> 
>                 Mock -CommandName Get-Command -MockWith { return @{Parameters = @{Name = 'MockName'}}}
> ```

Mock -CommandName Get-Command -MockWith {
    return @{
        Parameters = @{
            Name = 'MockName'
        }
    }
}

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/180)*

**Comment by kwirkykat** [comment]
Reviewed 1 of 11 files at r1, 11 of 21 files at r3.
Review status: 11 of 21 files reviewed at latest revision, 11 unresolved discussions.

---

*[Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMfftUhV3qJFcB2BzJS:-KMfftUhV3qJFcB2BzJT:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1#L6)):*
> ```PowerShell
> 
> #region HEADER
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1, line 7 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffsjR0zaJl2yfjZ7N:-KMffsjR0zaJl2yfjZ7O:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1#L7)):*
> ```PowerShell
> 
> # Integration Test Template Version: 1.1.0
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffrkJByctinsnaHW2:-KMffrkJByctinsnaHW3:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1#L6)):*
> ```PowerShell
> 
> #region HEADER
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffr1BtKfePAGYP5nh:-KMffr1BtKfePAGYP5ni:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1#L6)):*
> ```PowerShell
> #region HEADER
> # Integration Test Template Version: 1.1.0
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffqOKGwD2BtKzwf4-:-KMffqOLeRbuCnPytZgO:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1#L6)):*
> ```PowerShell
> #region HEADER
> # Integration Test Template Version: 1.1.0
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1, line 9 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffpOgLfMvQpluvrbN:-KMffpOgLfMvQpluvrbO:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1#L9)):*
> ```PowerShell
> 
> # Integration Test Template Version: 1.1.0
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1, line 8 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffm_lUO4mbfVOBT5S:-KMffm_lUO4mbfVOBT5T:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1#L8)):*
> ```PowerShell
> 
> # Integration Test Template Version: 1.1.0
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffliUm26OkZ6J-OUh:-KMffliUm26OkZ6J-OUi:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1#L5)):*
> ```PowerShell
> 
> #region HEADER
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffhnuxFz3coj4lQeC:-KMffhnuxFz3coj4lQeD:-430004021) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1#L6)):*
> ```PowerShell
> 
> #region HEADER
> $script:moduleRoot = Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $Script:MyInvocation.MyCommand.Path))
> ```

Replace with $PSScriptRoot

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 943 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffBfFxeDEnuY0LAqQ:-KMffBfFxeDEnuY0LAqR:-110629554) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Unit/MSFT_xWebsite.Tests.ps1#L943)):*
> ```PowerShell
>                 Mock -CommandName Get-Website
> 
>                 Mock -CommandName Get-Command -MockWith { return @{Parameters = @{Name = 'MockName'}}}
> ```

Change this one to the multi-line format too.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 1057 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMff6kE8mrAMBwOgv5c:-KMff6kFRspU-JiDhk1Z:-918288111) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1057)):*
> ```PowerShell
>                 Mock -CommandName Get-Website
> 
>                 Mock -CommandName Get-Command -MockWith { return @{Parameters = @{Name = 'MockName'}}}
> ```

This one too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/180)*

**Comment by mbreakey3** [comment]
Review status: 11 of 21 files reviewed at latest revision, 19 unresolved discussions.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 887 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMeza0UXKpPsHh0GsRD:-KMfAMpSvNs70d01wgMA:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L887)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Please add a help comment with a synopsis and description of the parameter.
</details>
Done.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 897 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf-ADeMoJ3gtQVRnYd:-KMfAOo7GrjXho6AYXwS:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L897)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Change to a multi-line <# #> comment.
</details>
Done.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 900 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMezxQA9_GLyvE20Zrx:-KMfAXRvh1KedyaZ6Jtb:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L900)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Rename variable to appCmdFilePath.
</details>
Done.

---

*[Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMfftUhV3qJFcB2BzJS:-KMfiUmfeQ_giLblks-C:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xIISHandler.Integration.Tests.ps1#L6)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1, line 7 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffsjR0zaJl2yfjZ7N:-KMfiWTaGdyNyv8QseUe:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_XIISLogging.Integration.Tests.ps1#L7)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffrkJByctinsnaHW2:-KMfiWyi6X2ZyOQd-VCl:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xIISMimeTypeMapping.Integration.Tests.ps1#L6)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffr1BtKfePAGYP5nh:-KMfiXcr1CRML-RwWDn3:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xSSLSettings.Integration.Tests.ps1#L6)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffqOKGwD2BtKzwf4-:-KMfiYHGWgYaS_jN75cr:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebApplication.Integration.Tests.ps1#L6)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1, line 9 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffpOgLfMvQpluvrbN:-KMfiYthPsEExPV-3-WF:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebAppPool.Integration.tests.ps1#L9)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1, line 8 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffm_lUO4mbfVOBT5S:-KMfiZU01FTAc--tMdFV:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebAppPoolDefaults.Integration.Tests.ps1#L8)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1, line 5 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffliUm26OkZ6J-OUh:-KMfi_1HrWF5FSM2bDb_:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebsite.Integration.Tests.ps1#L5)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1, line 6 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffhnuxFz3coj4lQeC:-KMfi__ENL20tDkGw_h0:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Integration/MSFT_xWebsiteDefaults.Integration.Tests.ps1#L6)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Replace with $PSScriptRoot
</details>
Done.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1, line 8 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf04ek01pehLahAa48:-KMfB6zKaCVYeB_Ln2Z_:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1#L8)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Remove [String]. It is not necessary. This should be in the script: scope. $Script:MyInvocation.MyCommand.Path should be removed and $PSScriptRoot should just be used instead to import modules so that the test doesn't rely on where the invocation happens.
</details>
Done.

---

*[Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1, line 62 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf0u9qSMO8KXE8_Fpn:-KMfBnqLEeFupcJ4ocPq:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xIISFeatureDelegation.tests.ps1#L62)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Change file name to MockWebAdministrationWindowsFeature.psm1 to make this more clear.
</details>
Done.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 106 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf2H1r3ZMNFgx2ksW-:-KMfZdAdpXSDZGrmDDMQ:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xWebsite.Tests.ps1#L106)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Add -MockWith named parameter.
</details>
Done.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 1012 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf2aW-6xCsSq2oDQQH:-KMf_QfFRHWJDmDL9Nkg:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1012)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Mock -CommandName Get-Command -MockWith {
>     return @{
>         Parameters = @{
>             Name = 'MockName'
>         }
>     }
> }
</details>
Done.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 943 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMffBfFxeDEnuY0LAqQ:-KMfj6W6O7mWXUF3JUWe:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Unit/MSFT_xWebsite.Tests.ps1#L943)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Change this one to the multi-line format too.
</details>
Done.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 1057 \[r3\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMff6kE8mrAMBwOgv5c:-KMfj6B7fd6AFecfvJ_2:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/2b322f14a52eac2e10e24b7c029e7465b2ca48d8/Tests/Unit/MSFT_xWebsite.Tests.ps1#L1057)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> This one too.
</details>
Done.

---

*[WebAministrationStubs.psm1, line 1 \[r2\]](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-KMf3NhHeICpfxJGHAkp:-KMf8bWcfuRVzkw1KI9U:-499146009) ([raw file](https://github.com/powershell/xwebadministration/blob/564e1e504850ecb9bd38f1e42bf7e2a5a2912afc/WebAministrationStubs.psm1#L1)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Mariah will fix the style here later if needed. This file should be renamed MockWebAdministrationWindowsFeature.psm1.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/180)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 10 of 10 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/180#-:-KMfjqW40aoqZtAAH94I:1417088721)*

**Pull request merged**
