### PR TITLE
Merge PSHOrg cAppPool to xWebAppPool

### PR DESCRIPTION
**Pull request by zuehlaa**
Merging all the community work done here https://github.com/PowerShellOrg/cWebAdministration on the cAppPool resource with the xWebAppPool resource.  Thanks @powershellorg

This is all the cAppPool code as of today.  The only thing added from xWebAppPool was the State option ("Started"/"Stopped")

I have tested this against 2008r2 and 2012r2.

### CODE REVIEW

**Comment by vors** [comment]
It's a big change, we would need original author of the resource review it.

**Comment by zuehlaa** [comment]
Not sure if you mean the original MS author or the author of the changes.  @smurawski committed the initial big change and the a few of us added on to it.  xWebsite is going to be the same way.  It barely resembles the original.  With these changes you can now pretty much configure any setting there is.  I'll try to get the xWebsite PR in tomorrow so that it can start to be reviewed.

**Comment by vors** [comment]
Yes, I was talking about MS authors. It would be great if @smurawski will take a look as well.

**Comment by vors** [comment]
@mhendric can you, please review this changes?

**Comment by smurawski** [comment]
@zuehlaa @vors @mhendric I would not take this change until we can wrap some tests around it.  I was working on some tests in the community fork, but haven't gotten very far.   I know there aren't currently any tests for the x resource and this is a major impediment to new development.  Given how big a change this is, I think tests are a reasonable requirement.

**Comment by TravisEz13** [comment]
@smurawski Agreed, we need a level of testing to be included before we can take the code.

**Comment by vors** [comment]
Adding to the list of 'c' to 'x' merge PRs https://github.com/PowerShell/DscResources/issues/27

**Comment by tysonjhayes** [comment]
So who or what are we waiting on for this? @smurawski to finish wirting the tests in the c resource? Or someone to write some tests for the x resource?

**Comment by smurawski** [comment]
Don't block on me, if someone else wants to get tests in place - go for it!

**Comment by vors** [comment]
@zuehlaa would you be able to include tests?

**Comment by zuehlaa** [comment]
I haven't used Pester before, but I can give it a shot

**Comment by vors** [comment]
We would much appreciate it. Don't hesitate to ask me any questions.

**Comment by zuehlaa** [comment]
I've added a couple initial tests.  Just want to make sure I'm on the right track before doing more.

**Comment by zuehlaa** [comment]
I'm going to stop now :)  until you guys let me know that this look ok or not.

**Comment by zuehlaa** [comment]
@vors Appveyor keeps throwing 
```
start-WebAppPool : Access is denied. (Exception from HRESULT: 0x80070005 (E_ACCESSDENIED))
At C:\projects\xwebadministration\DSCResources\MSFT_xWebAppPool\MSFT_xWebAppPool.psm1:343 char:21
+                     start-WebAppPool -Name $Name
+                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (IIS:\apppools\PesterAppPool:String) [Start-WebAppPool], UnauthorizedAccessException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.IIs.PowerShell.Provider.StartAppPoolCommand
```
Do I need to do something different?  The tests seems to work on my local machines.

**Comment by tysonjhayes** [comment]
Couple of thoughts. 
1) Totally works on my machine too. I'm not sure why it's throwing access denied.
2) Could you break up and group some of the tests together with a Context? For example. Group all Test-TargetResource calls together like so.

````
Context 'Test-TargetResource' {
    It 'Totally does everything I want' {
        $true | should be $true
   }
}

**Comment by zuehlaa** [comment]
I broke up the tests into 2 contexts and made it much easier to add new tests.

```
It 'Passes autoStart Test when same' {             
    TestTargetResourceSame "autoStart" "add.autoStart" | Should be $true
}

It 'Fails autoStart Test when different' {              
    TestTargetResourceDiff "autoStart" "add.autoStart" "true" "false"| Should be $false
 }

It 'Should set autoStart Test ' {             
    SetTargetResource "autoStart" "add.autoStart" "true" "false"| Should be $true
}
```

Not sure why it showed up as unknown on the commit and not me.

**Comment by KarolKaczmarek** [comment]
@TravisEz13 Can you take a look at this PR and the test failures?

**Comment by tysonjhayes** [comment]
Hi @zuehlaa - are you still working on this? It's been a while since we've seen any activity on this. If you are not working on this anymore (or I don't hear from you) I'm going to fork this and try to fix it up myself as we'd really like some of this functionality. Please let me know.

**Comment by zuehlaa** [comment]
I've been waiting to hear back from @KarolKaczmarek or @TravisEz13 before spending more time on it

**Comment by tysonjhayes** [comment]
Hi @zuehlaa could you resolve the merge conflicts and repush this so we can address whatever the current failures are? At this point this code is months out of date so we'll need to get it updated before we can being to address any of the problems.

**Comment by zuehlaa** [comment]
Crap, that didn't work right

**Comment by zuehlaa** [comment]
Not sure why all those extra file changes showed that shouldn't be there.  Nor do I know how to clean this up.  Should I close and start fresh with a new PR?

**Comment by tysonjhayes** [comment]
Yeah I'm pretty lost by what's going on with that.

**Comment by zuehlaa** [comment]
See https://github.com/PowerShell/xWebAdministration/pull/63

**Comment by tysonjhayes** [comment]
After reviewing this again I've got some suggestions.

* You shouldn't be modifying the system in a unit test, modifications should be done in an integration test setting.  

You noted you've never used Pester before, and that's OK! We all have to learn, god knows I had to learn with this. :grin:  

I'd recommend a couple of modifications to achieve this goal.

1) Add the following function to your xWebAppPool.psm1

````powershell
function Invoke-AppCmd
{
    param
    (
        [string[]] $Arguments,
        [string] $Path = "$env:SystemRoot\system32\inetsrv\appcmd.exe"
    )

    if (Test-Path $Path)
    {
        & $Path $Arguments
    }
    else
    {
        throw "$Path does not exist"
    }
}
````

Then anytime you call appcmd.exe instead of calling the exe directly call the function. So on line 800 the call becomes this:

````powershell
    $AppPool = Invoke-AppCmd -Arguments list,apppool,$Name
````

This allows you to mock Invoke-AppCmd and return whatever you desire.

````powershell
Context 'Test-TargetResource' {
    It 'Passes test when App Pool does exist and has the correct name'{
        $testParams = @{
            Name = "PesterAppPool"
            Ensure = "Present"
        }

        Mock Invoke-AppCmd {return $testParams}

        Test-TargetResource @testParams | Should be $true
    }

It 'returns false if autoStart is different' {

    $testParams = @{
        Name = "PesterAppPool"
        Ensure = "Present"
        AutoStart = 'False'
    }

    $failParams = $testParams
    $failParams['AutoStart'] = 'True'

    Mock Invoke-AppCmd {return $failParams}

    Test-TargetResource @testParams | Should be $false
}
````

Doing this allows you to run the same tests but control the outcome without having to make any modifications to the system.

**Comment by tysonjhayes** [comment]
Cool - I'm going to close this so we don't get confused. Thank you so much for following up on this.

**Comment by zuehlaa** [comment]
Nice, I like that.  I will get that done.

**Pull request closed without merging**
