### PR TITLE
xWebSite: Moved localization strings, and examples from README.md

### LINKED ISSUE #475: xWebSite: Move localization strings to strings.psd1 file
We should move the localization strings to a strings.psd1 file. See the localization https://dsccommunity.org/guidelines/localization/

### LINKED ISSUE #487: xWebSite: Move example from README.md to examples folder
This example https://github.com/PowerShell/xWebAdministration#create-a-new-website should be added as new example, and in the description for the comment-based help it should use the text that describing the example in the README.md.

### PR DESCRIPTION
**Pull request by hacky1997**
#### This Pull Request (PR) fixes the following issues
- Fixes #475
- Fixes #487
- Fixes #494

#### Task list

- [ ] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/490)

### CODE REVIEW

**Comment by johlju** [comment]
@hacky1997 Please sign the CLA for me to be able to review this PR. 

Also, please update the PR description with the issue this PR is closing.

**Comment by johlju** [comment]
@hacky1997 Thank you for signing the CLA. I will review this PR. 🙂

**Comment by hacky1997** [comment]
Sorry but I didn't understand what was my mistake !! could help me to sort out that? @johlju

**Comment by johlju** [comment]
I think all the changes you made got into this PR. I reviewing it now. This PR looks good so far, just a few review comments. 🙂

**Comment by hacky1997** [comment]
Yes I actually asking about the https://github.com/PowerShell/xWebAdministration/pull/494 this one @johlju

**Comment by johlju** [comment]
@hacky1997 to send in more than one PR you must branch out from the dev branch, read more here https://github.com/PowerShell/xWebAdministration/pull/493#issuecomment-536649491

**Comment by johlju** [comment]
@hacky1997 let me know if you need any help with this.

**Comment by hacky1997** [comment]
> @hacky1997 let me know if you need any help with this.

Sure, Actually in India, we people celebrate our Durga Puja festival. So that's why it takes much time to fixed those issues.

**Comment by johlju** [comment]
I think we need to take a step back a look how we should solve issue #487. It has evolved since other PRs have merged.

The example that issue #487 is pointing at I want split up each configuration block in two files. 

- First example configuration block I want to be moved in to a file named `Sample_xWebsite_NewWebsite_UsingCertificateThumbprint.ps1`, the file should be created in the folder Examples/Resources/xWebSite.
- Second example configuration block I want to be moved in to a file named `Sample_xWebsite_NewWebsite_UsingCertificateSubject.ps1`, the file should be created in the folder Examples/Resources/xWebSite.

The other example files in this PR should be removed so that only the two above that resolves issue #487 is left.

**Comment by hacky1997** [comment]
> I think we need to take a step back and look how we should solve issue #487. It has evolved since other PRs have merged.
> 
> The example that the issue #487 is pointing at, I want each configuration block split up into its own file (resulting in only two new example files).
> 
> * First example configuration block I want to be moved in to a file named `Sample_xWebsite_NewWebsite_UsingCertificateThumbprint.ps1`, the file should be created in the folder Examples/Resources/xWebSite.
> * Second example configuration block I want to be moved in to a file named `Sample_xWebsite_NewWebsite_UsingCertificateSubject.ps1`, the file should be created in the folder Examples/Resources/xWebSite.
> 
> The other example files in this PR should be removed so that only the two above that resolves issue #487 is left.

Done.

**Comment by johlju** [comment]
@hacky1997 We are close now! Thank you for the work you put into this PR! 😃

**Comment by hacky1997** [comment]
Could you please remove the invalid label if you don't mind!

**Comment by johlju** [comment]
When you merged lates changes from you did not resolve the README.md correctly. You got a lot of text in it again that should not be part of this PR. :) Could you please look a that again?

**Comment by hacky1997** [comment]
> When you merged lates changes from you did not resolve the README.md correctly. You got a lot of text in it again that should not be part of this PR. :) Could you please look at that again?

Resolve means conflicts? or I have to delete Sample_xWebsite_NewWebsite this from readme.md file?

**Comment by johlju** [comment]
@hacky1997 Thank you for this! I will merge this as soon as the test passed. 😃

**Comment by hacky1997** [comment]
@johlju Thank you so much. Without you it is tough for me and honestly I learn a lot from this. Again, Thank you so much. I hope I will contribute more in future :)

**Comment by johlju** [comment]
@hacky1997 happy to help :)

**Pull request merged**
