### PR TITLE
449 reorder

### LINKED ISSUE #449: Reorder resources alphabetically in README.md
In the README.md the resources are not in alphabetical order, so it's harder to find a resource. We should move these in alphabetical order.

### PR DESCRIPTION
**Pull request by midacts**
Fixes #449

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/498)

### CODE REVIEW

**Comment by midacts** [comment]
if you let me know what's wrong, i'll fix it for the PR.

**Comment by X-Guardian** [comment]
You need to resolve the merge conflicts on the README.md. I would also suggest rebasing as you are including commits from other PRs. See [Resolve Merge Conflicts](https://github.com/PowerShell/DscResources/blob/master/GettingStartedWithGitHub.md#resolve-merge-conflicts) for instructions on how to do this.

**Comment by midacts** [comment]
It looks like this repo used `dev` as the main branch and not `master`?

**Comment by X-Guardian** [comment]
Yes, that is standard for all the Dsc repos.

**Comment by midacts** [comment]
#502 - opened this PR instead as i didnt know how to just work from dev.

so i just started fresh from dev.

**Pull request closed without merging**
