### PR TITLE
adding back changes from overwritten PR

### PR DESCRIPTION
**Pull request by mbreakey3**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/203)

### CODE REVIEW

**Comment by mbreakey3** [comment]
@kwirkykat could you take a quick look at this PR?

**Comment by kwirkykat** [comment]
Reviewed 17 of 20 files at r1.
Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 912 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORlc8SyVllXqcP4YTM:-KORlc8SyVllXqcP4YTN:b-2o5dbm) ([raw file](https://github.com/powershell/xwebadministration/blob/2866a0895c5a0f12ff67d41707ea5eb1f06fbd3d/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L912)):*
> ```PowerShell
>     $appcmdFilePath = "$env:SystemRoot\System32\inetsrv\appcmd.exe"
> 
>     $(& $appcmdfilePath $ArgumentList) | Write-Verbose
> ```

Just for clarity, can you change this to something along the lines of:
```powershell
$appcmdResult = $(& $appcmdFilePath $ArgumentList)
Write-Verbose -Message $appcmdResult
```

---

*[Tests/Unit/MSFT_xWebApplication.Tests.ps1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORnjCzC7F8pPbhec2X:-KORnjD-w6uE0WCO5Ob9:bqwcch6) ([raw file](https://github.com/powershell/xwebadministration/blob/2866a0895c5a0f12ff67d41707ea5eb1f06fbd3d/Tests/Unit/MSFT_xWebApplication.Tests.ps1#L102)):*
> ```PowerShell
>                     -ParameterFilter { ($Type -eq 'Windows') }
> 
>                 Mock -CommandName Assert-Module -MockWith {}
> ```

Why are these mocks redefined in each Context? (rather than defined once in the Describe)

---

*[Tests/Unit/MSFT_xWebAppPool.Tests.ps1, line 3300 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORojC54TPXoyRdKC_W:-KORojC6HNwafWFM-vRY:b-mnes52) ([raw file](https://github.com/powershell/xwebadministration/blob/e300233a159a89274ba44b75d5ae1527abbd4344/Tests/Unit/MSFT_xWebAppPool.Tests.ps1#L3300)):*
> ```PowerShell
>         Describe "$($script:DSCResourceName)\Invoke-AppCmd" {
> 
>             It 'Should throw if AppCmd.exe exits with non-zero exit code' {
> ```

Why was this test taken out?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/203)*

**Comment by mbreakey3** [comment]
Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1, line 912 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORlc8SyVllXqcP4YTM:-KORr74v6PqXf4YQIokt:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/2866a0895c5a0f12ff67d41707ea5eb1f06fbd3d/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L912)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Just for clarity, can you change this to something along the lines of:
> ```powershell
> $appcmdResult = $(& $appcmdFilePath $ArgumentList)
> Write-Verbose -Message $appcmdResult
> ```
</details>
Done.

---

*[Tests/Unit/MSFT_xWebApplication.Tests.ps1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORnjCzC7F8pPbhec2X:-KORsMfBB1jdeYin--Rb:bbr87ys) ([raw file](https://github.com/powershell/xwebadministration/blob/2866a0895c5a0f12ff67d41707ea5eb1f06fbd3d/Tests/Unit/MSFT_xWebApplication.Tests.ps1#L102)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Why are these mocks redefined in each Context? (rather than defined once in the Describe)
</details>
Well some of them return different things, but I can move some of the duplicates up

---

*[Tests/Unit/MSFT_xWebAppPool.Tests.ps1, line 3300 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORojC54TPXoyRdKC_W:-KORsRzyuHy0BhDluuY-:bjihq4l) ([raw file](https://github.com/powershell/xwebadministration/blob/e300233a159a89274ba44b75d5ae1527abbd4344/Tests/Unit/MSFT_xWebAppPool.Tests.ps1#L3300)):*
<details><summary><i>Previously, kwirkykat (Katie Keim) wrote…</i></summary>
> Why was this test taken out?
</details>
I talked with Travis about this. We simplified the function and the only way to really test this function is with an integration test so we're just removing it for now

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/203)*

**Comment by mbreakey3** [comment]
Review status: 17 of 20 files reviewed at latest revision, 3 unresolved discussions.

---

*[Tests/Unit/MSFT_xWebApplication.Tests.ps1, line 102 \[r1\]](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-KORnjCzC7F8pPbhec2X:-KORsuqFSGUFdC3n7caT:b-ab5rmt) ([raw file](https://github.com/powershell/xwebadministration/blob/2866a0895c5a0f12ff67d41707ea5eb1f06fbd3d/Tests/Unit/MSFT_xWebApplication.Tests.ps1#L102)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary>
> Well some of them return different things, but I can move some of the duplicates up
</details>
This file is also not one of the ones being published in WebAdministrationDsc, so we can worry about some of the existing style issues in a later issue

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/203)*

**Comment by kwirkykat** [comment]
:lgtm:

---

Reviewed 1 of 20 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/203#-:-KORuqOfyGpWKzY5qpnc:bnfp4nl)*

**Pull request merged**
