### PR TITLE
Added LogCustomFields to xWebSite (Fixes #267)

### LINKED ISSUE #267: Support for custom field(s) logging
We should have support to enable custom field(s) to IIS logging.

I can probably create that feature but how you think that it should be implemented?

Example "X-Forwarded-For" header can be included to logging using this PowerShell command:
`Add-WebConfigurationProperty -pspath 'MACHINE/WEBROOT/APPHOST'  -filter "system.applicationHost/sites/siteDefaults/logFile/customFields" -name "." -value @{logFieldName='Original-IP';sourceName='X-Forwarded-For';sourceType='RequestHeader'}`

It needs these four parameters:
- Site name/Site defaults selection
- Field name where value will be stored on log
- Source parameter name where value will be read
- Source type, valid inputs are "RequestHeader","ResponseHeader" and "ServerVariable"

Do you prefer that this should be included to existing "xIISLogging" and "xWebsite" modules (and if so how to do input validation correct way?) or would it be better idea create new "xIISCustomLogging", etc module?

### PR DESCRIPTION
**Pull request by regedit32**
Modified xWebSite to include the ability to manage logging custom fields. (Fixes #267 )
Below is an example of how to add a logging custom field with the updated resource:
```
xWebsite NewWebsite
{
    Ensure             = 'Present'
    Name               = 'Default Web Site'
    LogCustomFields    = MSFT_xLogCustomFieldInformation
    {
        LogFieldName   = 'Original-IP'
        SourceName     = 'X-Forwarded-For'
        SourceType     = 'RequestHeader'
    }
}
```

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342)

### CODE REVIEW

**Comment by johlju** [comment]
Awesoem work on this one! :smile: Just a few review comments. 

---

Reviewed 4 of 7 files at r1, 1 of 2 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[README.md, line 170 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmTJC9AqW_7fXhgLbZ:-LAmTJC9AqW_7fXhgLb_:beaio56) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/README.md#L170)):*
> ```
> informationin
> ```

information

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 770 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmSBmxAQkQ6KIEdGtT:-LAmSBmxAQkQ6KIEdGtU:bri0ogg) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L770)):*
> ```PowerShell
>             }
> 
>             # Update LogCustomFields if neeed
> ```

Instead of duplicating this code twice, can't we just run this once after the evaluation if the website should be created or already exists?

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 1090 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmSml15gxqmOUbwEm9:-LAmSml15gxqmOUbwEmA:b-2khrg6) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1090)):*
> ```
> neeed
> ```

We should have two 'e' here :) Throughout.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 1634 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmOfzH2bUe39ZnzAGn:-LAmOfzH2bUe39ZnzAGo:bt2r7ox) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1634)):*
> ```PowerShell
> {
>     [CmdletBinding()]
>     [OutputType([Microsoft.Management.Infrastructure.CimInstance])]
> ```

Should return an array of CimInstance's not just one?

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 1860 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmPDgt-e7GzazFxqLv:-LAmPDgt-e7GzazFxqLw:b-rzrtqx) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1860)):*
> ```PowerShell
>     Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.applicationHost/sites/site[@name='$Site']/logFile/customFields" -Name "." -Value $setCustomFields
> 
>     # The second Set-WebConfigurationProperty is to handle an edge case where logfile.customFields is not updated correctly.  May be caused by a possible bug in the IIS provider
> ```

Could we instead loop twice over one of the `Set-WebConfigurationProperty`?

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 1860 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmPXrbAeqzD4GCA3o_:-LAmPXrbAeqzD4GCA3oa:b-r1nkho) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L1860)):*
> ```PowerShell
>     Set-WebConfigurationProperty -PSPath 'MACHINE/WEBROOT/APPHOST' -Filter "system.applicationHost/sites/site[@name='$Site']/logFile/customFields" -Name "." -Value $setCustomFields
> 
>     # The second Set-WebConfigurationProperty is to handle an edge case where logfile.customFields is not updated correctly.  May be caused by a possible bug in the IIS provider
> ```

Could you please submit an issue for this in this repo so this can be tracked. I will label it as external though, since we can't do anything about it in this repo. But once fixed we can remove the workaround.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 2154 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmQI2yAfafuoL0IcEn:-LAmQI2yAfafuoL0IcEo:b-9xulm2) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L2154)):*
> ```
> sourceName
> ```

Should we have upper 'S' on this property name? Same for the row below.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 2156 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmQ7eTAFd2NbwbDD-K:-LAmQ7eTAFd2NbwbDD-L:b-s45hy4) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L2156)):*
> ```PowerShell
>             $sourceNameMatch = $customField.SourceName -eq $presentCustomField.sourceName
>             $sourceTypeMatch = $customField.SourceType -eq $presentCustomField.sourceType
>             if(-not ($sourceNameMatch -and $sourceTypeMatch))
> ```

Please add a space between if an the parenthesis .

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof, line 54 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmTO4nCGtR1RQ_CUB2:-LAmTO4nCGtR1RQ_CUB3:bknj3h7) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/DSCResources/MSFT_xWebsite/MSFT_xWebsite.schema.mof#L54)):*
> ```
>     [Write, Description ("Use the localtime for file naming and rollover")] Boolean LoglocalTimeRollover;
>     [Write, Description ("Format of the Logfiles. Only W3C supports LogFlags"), ValueMap{"IIS","W3C","NCSA"}, Values{"IIS","W3C","NCSA"}] String LogFormat;
>     [Write, EmbeddedInstance("MSFT_xLogCustomFieldInformation"), Description("Custom logging field information")] String LogCustomFields[];
> ```

Could we extent this description a bit to something more like that first phrase in the README.md?

---

*[Tests/Integration/MSFT_xWebsite.config.ps1, line 157 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmTzL-7zI2fkTEl4of:-LAmTzL-7zI2fkTEl4og:b-xrlacj) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/Tests/Integration/MSFT_xWebsite.config.ps1#L157)):*
> ```PowerShell
>                     LogFieldName = $Node.LogFieldName
>                     SourceName   = $Node.SourceName
>                     SourceType   = $Node.SourceType
> ```

Maybe we could add another SourceType for this test?

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 84 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmViqi-_m3gKL11iLR:-LAmVZeD5qbXKp-mlI1U:b1qjn1y) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L84)):*
> ```
> $MockLogCustomFields
> ```

Could we start the variable names with lower-case? Throughout (only have to do  on your changes).

I know the others aren't, but we need to start somewhere to follow the guideline :smile: 

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 97 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmV9gj24GqHpGHAd1V:-LAmV9gj24GqHpGHAd1W:b-bchc5m) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L97)):*
> ```PowerShell
>                 truncateSize      = '1048576'
>                 localTimeRollover = 'False'
>                 customFields      = @{Collection = @($MockLogCustomFields)}
> ```

Since we can add an array maybe we should test with an array of two objects? Throughout.

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 3529 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmYcxqAfhCyDXyJ0X_:-LAmYcxqAfhCyDXyJ0Xa:b42i28g) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L3529)):*
> ```PowerShell
> 
>             Context 'Expected behavior'{
>                 $Result = ConvertTo-CimLogCustomFields -InputObject $MockLogCustomFields
> ```

Maybe test this with an array?

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 3569 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmYzXA8UpCLg6gWD_G:-LAmYzXA8UpCLg6gWD_H:b42i28g) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L3569)):*
> ```PowerShell
> 
>                It 'should return True' {
>                     Test-LogCustomField -Site $MockWebsiteName -LogCustomField $MockCimLogCustomFields | Should Be $True
> ```

Maybe test this with an array?

---

*[Tests/Unit/MSFT_xWebsite.Tests.ps1, line 3615 at r3](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-LAmZ8p2C-n6H_xLKA71:-LAmZ8p2C-n6H_xLKA72:b42i28g) ([raw file](https://github.com/powershell/xwebadministration/blob/df709b7cf13aba24a191aba8392c972e364ed99a/Tests/Unit/MSFT_xWebsite.Tests.ps1#L3615)):*
> ```PowerShell
> 
>                 It 'should not throw an error' {
>                     { Set-LogCustomField  -Site $MockWebsiteName -LogCustomField $MockCimLogCustomFields } | Should Not Throw
> ```

Maybe test this with an array?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/powershell/xwebadministration/342#-:-LAmZLXzCaQCkfIUJT6k:b-xx4er6)*

**Comment by johlju** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342)*

**Comment by johlju** [comment]
@regedit32 Can you rebase this one to resolve the merge conflicts? Also, when you push next time the tests should pass, we got fixes merged for the failing tests.

**Comment by regedit32** [comment]
@johlju  done, thanks.

---

Review status: 5 of 8 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342#-:-LBXNOOi-XFG5XOAf3vM:bhs59z4)*

**Comment by johlju** [comment]
Just a tiny review comment left, I must have missed it before.

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 265 at r5](https://reviewable.io/reviews/powershell/xwebadministration/342#-LBezE5uD3gSXOX8UAbe:-LBezE5uD3gSXOX8UAbf:b-944dlg) ([raw file](https://github.com/powershell/xwebadministration/blob/e57ff3778941eceb7dfbebd951e9b7cb81c7ca3d/README.md#L265)):*
> ```Markdown
> ### Unreleased
> * Updated **xWebSite** to include ability to manage custom logging fields
> ```

Can we remove this extra blank line?

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342#-:-LBezT4P2XAJyWbPYNqW:b-dlsb3f)*

**Comment by regedit32** [comment]
done.  Did another rebase and it took care of that, thanks.

---

Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342#-:-LBfB-18DvyDOBq4jct6:b-3estj8)*

**Comment by regedit32** [comment]
Review status: 7 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 265 at r5](https://reviewable.io/reviews/powershell/xwebadministration/342#-LBezE5uD3gSXOX8UAbe:-LBfBF7j3cC4j_dfwU1M:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/e57ff3778941eceb7dfbebd951e9b7cb81c7ca3d/README.md#L265)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Can we remove this extra blank line?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/342#-:-LBfDIIuBHIvQo1keCfR:bnfp4nl)*

**Comment by johlju** [comment]
@regedit32 Awesome work on this one! Thanks!

**Pull request merged**
