### PR TITLE
xWebAdministration_mhendric

### PR DESCRIPTION
**Pull request by mhendric**
Not sure why an extra line was added to all these files. The only files I actually touched were MSFT_xWebConfigKeyValue.schema.mof, and TechNetDocumentation_xWebAdministration.html. Let me know if this is a problem. Note that I did NOT increment the build number in xWebAdministration.psd1.

### CODE REVIEW

**Comment by vors** [comment]
Did you use [fixers](https://github.com/PowerShell/DscResource.Tests/blob/master/MetaFixers.psm1)? Can it be, because of the problem in one of them?

**Comment by mhendric** [comment]
I did use the Unicode and spacer fixers on the whole module. Should I not do that?

Sent from my Windows Phone
________________________________

**Comment by vors** [comment]
You should, unfortunately there is a bug in one of the fixers https://github.com/PowerShell/DscResource.Tests/issues/1 I'm working on fixing it.

**Comment by vors** [comment]
I fixed problem with extra new lines produced by fixer. Thank you for point it out!

**Comment by mhendric** [comment]
Do I need to redo this change request using the updated tools so that there aren’t unnecessary files being modified?

**Comment by vors** [comment]
It's fine as is. Thank you!

**Pull request merged**
