### PR TITLE
Added Default Application Pool Properties to the xWebAppPoolDefaults Resource

### PR DESCRIPTION
**Pull request by mmcelreath**
Added Default Application Pool Properties to the xWebAppPoolDefaults Resource. Also added helper
function called GetValueType to help when setting new values.

### CODE REVIEW

**Comment by tysonjhayes** [comment]
Hi, sorry for the delay in responding here. Could you please add some tests to this to cover the new functionality you are adding?

**Comment by tysonjhayes** [comment]
Hi, haven't heard anything from you in a while, are you still working on this?

**Comment by tysonjhayes** [comment]
As I haven't heard from you I'm going to go ahead and close this. Please feel free to reopen it with the added tests and I'll get it merged.

**Comment by mmcelreath** [comment]
Sorry, I got caught up with a couple other projects. I'll circle back to this when I get more time.

On another note, I wanted to run something by you. Adding App Pool Properties to this resource could get pretty bloated with the amount of properties available to configure. We have someone in house who created a custom resource which sets the app pool default settings in a different way. Instead of having a parameter for each available property, this resource on uses Filter, Name and Value. This way you can set any app pool default property without having to hard code all of those parameters. For example, setting autoStart to True would be done like this:

WebConfigurationProperty ApplicationPoolDefaults_AutoStart
    {
        Filter = "/system.applicationHost/applicationPools/applicationPoolDefaults"
        Name = "autoStart"
        Value = "True"
    } 

I'm wondering if this would be a better way to approach this within this resource. Thoughts?

**Pull request closed without merging**
