### PR TITLE
xWebSite: Fix for the issue #332

### LINKED ISSUE #332: BUG in SSL certificates assignment to bindings
Repro:
```PowerShell
$BindingInfo = @(
    New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
        Protocol              = 'https'
        IPAddress             = '*'
        Port                  = 443
        HostName              = 'api.bittitan.com'
        CertificateThumbprint = '34AE59F4CFA28602716C46D172850747B36624D8'
        CertificateStoreName  = 'WebHosting'
        SslFlags              = 1
    } -ClientOnly
    New-CimInstance -ClassName MSFT_xWebBindingInformation -Namespace root/microsoft/Windows/DesiredStateConfiguration -Property @{
        Protocol              = 'https'
        IPAddress             = '*'
        Port                  = 443
        HostName              = '*.migrationwiz.com'
        CertificateThumbprint = 'DE0A409C2F2BF8DF47C9154EDE3C3309CAB9E0F7'
        CertificateStoreName  = 'WebHosting'
        SslFlags              = 1
    } -ClientOnly
)

Update-WebsiteBinding -Name MigrationWiz -BindingInfo $BindingInfo
```
Despite different CertificateThumbprint specified for the first and second binding BOTH get the same (first) certificate assigned!

### PR DESCRIPTION
**Pull request by konste**
@johlju , here you go - one line fix!

Fixes #332 

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/347)

### CODE REVIEW

**Comment by johlju** [comment]
Thanks for this! Appreciate you resolving this! :smile: 

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/347#-LAriJj-3btjDES9E1NB:-LAriJj02K4Y1CER4Dmo:b-3cueiz) (no related file):*
Could you please add a regression unit test that tests multiple certificates so the result of this is correct and we don't get this problem down the road? 

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/347#-LArid-x67X7JSYanawz:-LArid-x67X7JSYanax-:b-46ncoo) (no related file):*
Please add a new entry to the change log for this change.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/347#-:-LArhw_c7GsP2g7N5hfo:bh57x7v)*

**Comment by johlju** [comment]
Labeling this PR as abandoned since it has gone 14 days or more since the last update. An abandoned PR can be continued by another contributor. The abandoned label will be removed if work on the PR is taken up again.

**Comment by gaelcolas** [comment]
Seems like a tiny change to get that fix in, so I removed the abandoned label and will try to get back to it in the near future.

@konste if you have time to solve the points made in the review that'd be much appreciated (especially the entry in release notes).

**Comment by mcbobke** [comment]
This issue is affecting our organization as well, and we had to disable DSC configuration of our web bindings for the time being. Just to confirm, all that's needed is a test and a change log entry before it can be merged, right?

**Comment by konste** [comment]
Right.

**Comment by johlju** [comment]
@mcbobke yes, just a regression test (that would fail if this change is not applied), and a change log entry explaining what the change resolves. 

Tag me for review as soon as that is resolved in this PR or another PR is sent in that closes this one, whatever is simplest. :smile:

**Comment by mcbobke** [comment]
Sounds good! I'll be working on this.

**Comment by konste** [comment]
I am sorry, I left this area a while ago. @mcbobke please let me know if you need anything from me to push the fix through.

**Comment by mcbobke** [comment]
I appreciate the offer @konste ! I just created #437 to move forward from here.

**Pull request closed without merging**
