### PR TITLE
Removed "Create and Configure application pool" example.

### PR DESCRIPTION
**Pull request by Abijith10**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/493)

### CODE REVIEW

**Comment by Abijith10** [comment]
@johlju Is it right now?

**Comment by johlju** [comment]
@Abijith10 It looks better thank you! 😃

**Comment by Abijith10** [comment]
@johlju I am up on another task, can I have your guidance on it?

**Comment by johlju** [comment]
I will merge a PR is a bit (waiting for the tests to pass) that moves the change log to a CHANGELOG.md. Can you please add a change log entry to to this PR once I done that. I will make a review comment at that time.

@Abijith10 Yep, just comment in the issue you are working on and I'm happy to help.

**Comment by Abijith10** [comment]
Sure I am happy to edit the changelog but I couldn't locate the file. Can you please help me on that one.

**Comment by johlju** [comment]
Sorry, the CHANGELOG.md is not there yet 🙂  I'm waiting for PR https://github.com/PowerShell/xWebAdministration/pull/480 to pass it test run so I can merge it.

**Comment by Abijith10** [comment]
Oh fine then! I need help regarding the next issue.

**Comment by Abijith10** [comment]
@johlju Need your help here. I can't push a commit to my fork. My new commit ends up being here. What do I do?

**Comment by johlju** [comment]
@Abijith10 That's because you need to use different working branches for each PR. 🙂 Use for example `git checkout -b fix-issue-xxxx` to create a working branch named `fix-issue-xxxx`. Remember to first do `git checkout dev` because the new branch should be based on dev.

So
```
git checkout dev
git checkout -b fix-issue-xxxx
```

**Comment by Abijith10** [comment]
Oh! I did make a new branch but I made it from the master the first time. Now by using the dev branch, I can see the changes I did is undone.
So making a pull request from this one won't result in merge conflict?

**Comment by johlju** [comment]
The correct way is to always create a new branch from the repository default branch, in our case the dev branch. Each working branch (with different changes) can be sent in as new pull request. When merging the first one, the second PR will have merge conflicts, most likely in the change log, that need to be resolved.

**Comment by johlju** [comment]
@Abijith10 Please update the CHANGELOG.md according to the review comment. If this is not update within two days I will close this PR as invalid.

**Comment by johlju** [comment]
Since I have not seen any progress on this PR so I will close it as invalid as this time. If you want to work on this, then please reopen this PR.

**Pull request closed without merging**
