### PR TITLE
cast $cimLogCustomFields as array fixes #372

### LINKED ISSUE #372: Get-DscConfiguration will throw when xWebsite returns $null LogCustomFields
Get-DscConfiguration is very particular about the data type that is returned.  In the MOF String LogCustomFields is defined as an array, but if $website.logFile.customFields.Collection is $null, then $null is  being included in the Get return, which is not the same as an empty array.  $cimLogCustomFields should be casted as an array.

### PR DESCRIPTION
**Pull request by regedit32**
Fix for #372 .  

Also looks like my vscode settings cleaned up a bunch of white space.

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/373)

### CODE REVIEW

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed, 2 unresolved discussions (waiting on @regedit32)

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/373#-LFLaCmm9m4kzd10V2OM:-LFL_ZeM0aF_E4pacfGb:bgx6ujw) (no related file):*
Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 136 at r1](https://reviewable.io/reviews/powershell/xwebadministration/373#-LFLa5ZwDpA5BsyYKNDr:-LFLa5ZwDpA5BsyYKNDs:b-ii1ty0) ([raw file](https://github.com/powershell/xwebadministration/blob/738c71d9a597162cd5b4c63c8668f2cb0e6b6cc2/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L136)):*
> ```
> [Array]$cimLogCustomFields
> ```

`[Array] $cimLogCustomFields` (space after type).

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/373)*

**Comment by regedit32** [comment]
Review status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @johlju)

---

*[a discussion](https://reviewable.io/reviews/powershell/xwebadministration/373#-LFLaCmm9m4kzd10V2OM:-LFMguVDE-TaPjOjKLBu:b-896fix) (no related file):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Could you please add an descriptive entry, for each change/issue, to the Unreleased section of the change log in the file README.md? If an entry resolves an issue please reference the issue where applicable. You may suffix (it's optional) each entry with your name. Example of the format for the entry.
```
* Descriptive entry ([issue #123](https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/123). [Name/Alias (@github_account)](https://github.com/github_account)
```

</blockquote></details>

Done.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 136 at r1](https://reviewable.io/reviews/powershell/xwebadministration/373#-LFLa5ZwDpA5BsyYKNDr:-LFMgvji9trP-VTWNXvQ:b-896fix) ([raw file](https://github.com/powershell/xwebadministration/blob/60ccba93bae91d986227ba50fc5b5859e43f6308/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L136)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

> ```
> [Array]$cimLogCustomFields
> ```

`[Array] $cimLogCustomFields` (space after type).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/373)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: :shipit: complete! all files reviewed, all discussions resolved

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/373#-:-LFQt0F5748FF6R27Mbl:bnfp4nl)*

**Comment by johlju** [comment]
@regedit32 Thanks for fixing this! You are doing awesome work with these resources! 😃

**Comment by regedit32** [comment]
@johlju thank you!

**Pull request merged**
