### PR TITLE
xWebSite: Fixed errors when setting log properties (issue #299)

### LINKED ISSUE #299: xWebSite: bug when setting log properties
Hello everybody,

I am getting an error setting the log file rollover schedule for a web site in IIS 7.5. The following script

```PowerShell
Configuration TestConfiguration
{
    Import-DscResource –ModuleName PSDesiredStateConfiguration
    Import-DscResource -ModuleName xWebAdministration

    Node localhost
    {
        WindowsFeature IIS
        {
            Ensure = "Present"
            Name = "Web-WebServer"
        }

        xWebsite DefaultSite
        {
            Ensure    = "Present"
            Name      = "Default Web Site"
            LogFormat = "W3C"
            LogPeriod = "Hourly"
            DependsOn = "[WindowsFeature]IIS"
        }
    }
}
```
gives me the error:

_Hourly is not a valid value for Int32_

I don't get the error when the target setting is already _Hourly_.

I realized that even when the command `Get-ItemProperty -Path "IIS:\Sites\Default Web Site" -Name LogFile.period` gives me _Hourly_, the command `Set-ItemProperty -Path "IIS:\Sites\Default Web Site" -Name LogFile.period -Value "Hourly"` throws the error _Set-ItemProperty : Hourly is not a valid value for Int32_.

The error doesn't occour in IIS 8.0.

My environment is:

- Windows Server 2008 R2 Standard 6.1 (Build 7601: Service Pack 1)
- IIS 7.5
- PowerShell 5.0
- xWebAdministration 1.17.0.0
- Microsoft.IIS.PowerShell.Provider.dll version 7.5.7600.16385
- Microsoft.IIS.PowerShell.Framework.dll version 7.5.7600.16385
- Microsoft.Web.Administration.dll version 6.1.7601.17514

Any ideas? Thank you!

### PR DESCRIPTION
**Pull request by rosberglinhares**
Fixes the _Hourly is not a valid value for Int32_ error when setting the xWebSite LogPeriod in IIS 7.5. The solution was to set the value using numbers instead of strings when the OS version is prior to Windows Server 2012.

Fixes #299

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/300)

### CODE REVIEW

**Comment by rosberglinhares** [comment]
There is a related error when setting the LogFlags too. I can upload a new commit in this pull request fixing this error.

**Comment by tysonjhayes** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 443 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/300#-KnGSChoz5B3l9wzqAf0:-KnGSChoz5B3l9wzqAf1:b-y20ogq) ([raw file](https://github.com/powershell/xwebadministration/blob/24220783d77b9deb14a5dc833e0fc511ae4157d3/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L443)):*
> ```PowerShell
>                 {
>                     $site = Get-Item "IIS:\Sites\$Name"
>                     $site.LogFile.logFormat = $LogFormat
> ```

Why do we need an if/else here? Wouldn't what works in 2008 R2 work in 2012?   In other words, if Set-ItemProperty doesn't work in 2008R2 why don't we just use the else logic?

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 493 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/300#-KnGTBZOt3fh7yEmhV9A:-KnGTBZOt3fh7yEmhV9B:bcd29gn) ([raw file](https://github.com/powershell/xwebadministration/blob/24220783d77b9deb14a5dc833e0fc511ae4157d3/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L493)):*
> ```PowerShell
>                     $site = Get-Item "IIS:\Sites\$Name"
>                     $site.LogFile.period = $LogPeriod
>                     $site | Set-Item
> ```

Same comment of the if/else here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/300)*

**Comment by rosberglinhares** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 443 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/300#-KnGSChoz5B3l9wzqAf0:-KnL8Ivwsjh9CPiEhNuu:b-m1k3lm) ([raw file](https://github.com/powershell/xwebadministration/blob/24220783d77b9deb14a5dc833e0fc511ae4157d3/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L443)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Why do we need an if/else here? Wouldn't what works in 2008 R2 work in 2012?   In other words, if Set-ItemProperty doesn't work in 2008R2 why don't we just use the else logic?
</blockquote></details>

My intention was reduce the risk by not changing the working code for Windows Server 2012 and later systems, but it is really better to just use the else code. I already have the changed code. Should I push it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/300)*

**Comment by tysonjhayes** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 443 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/300#-KnGSChoz5B3l9wzqAf0:-KnamRMnRicvGSIp2-5h:b4t5vyb) ([raw file](https://github.com/powershell/xwebadministration/blob/24220783d77b9deb14a5dc833e0fc511ae4157d3/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L443)):*
<details><summary><i>Previously, rosberglinhares (Rosberg Linhares) wrote…</i></summary><blockquote>

My intention was reduce the risk by not changing the working code for Windows Server 2012 and later systems, but it is really better to just use the else code. I already have the changed code. Should I push it?
</blockquote></details>

Yes push it please. I'd prefer better code. We'll be testing on a 2012R2 system and should catch any issues.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/300)*

**Comment by rosberglinhares** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1, line 443 at r2](https://reviewable.io:443/reviews/powershell/xwebadministration/300#-KnGSChoz5B3l9wzqAf0:-Knh-WHgVKqXS4wM0zvC:b-896fja) ([raw file](https://github.com/powershell/xwebadministration/blob/24220783d77b9deb14a5dc833e0fc511ae4157d3/DSCResources/MSFT_xWebsite/MSFT_xWebsite.psm1#L443)):*
<details><summary><i>Previously, tysonjhayes (Tyson J. Hayes) wrote…</i></summary><blockquote>

Yes push it please. I'd prefer better code. We'll be testing on a 2012R2 system and should catch any issues.
</blockquote></details>

Done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/300)*

**Comment by tysonjhayes** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwebadministration/300)*

**Pull request merged**
