### PR TITLE
xWebsite/xIISLogging: Get-TargetResource returns expected array of individual log flags instead of a single comma-separated string

### LINKED ISSUE #405: xWebsite - Get-TargetResource returns LogFlags as a single element array instead of an array of strings
#### Details of the scenario you tried and the problem that is occurring
When running the xWebsite function Get-TargetResource the LogFlags key of the hashtable of data returned contains a single string element of all log flags separated by a comma. Expected behavior is a multi-element array where each element contains 1 log flag.

### First, I copied all content of MSFT_xWebsite.psm1 into my current environment
PS> $resource = Get-TargetResource <SiteName>

# Visual representation of what is stored in LogFlags
PS> $resource.LogFlags
Date,Time,ClientIP,UserName,SiteName,ComputerName,ServerIP,Method,UriStem,UriQuery,HttpStatus,Win32Status,BytesSent,BytesRecv,TimeTaken,ServerPort,UserAgent,Referer,ProtocolVersion,Host,HttpSubStatus

# Measuring the object to verify LogFlags is only 1 element
PS> $resource.LogFlags| measure
Count    : 1
...

# Measure of how many elements should have been in LogFlags
PS> $resource.LogFlags.Split(',') | measure
Count    : 21
...

#### Suggested solution to the issue
In Get-TargetResource change the following line (163 as of v2.2.0.0):
LogFlags                 = [Array]$website.logfile.LogExtFileFlags

to
LogFlags                 = [Array]$website.logfile.LogExtFileFlags.Split(',')

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
None, this is a manually generated issue that would only be seen when calling Get-DscConfiguration

# insert configuration here
No configuration used, this happens for any website defined

#### The operating system the target node is running
OsName               : Microsoft Windows Server 2012 R2 Standard
OsOperatingSystemSKU : StandardServerEdition
OsArchitecture       : 64-bit
WindowsBuildLabEx    : 9600.19153.amd64fre.winblue_ltsb.180908-0600
OsLanguage           : en-US
OsMuiLanguages       : {en-US}

#### Version and build of PowerShell the target node is running
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

#### Version of the DSC module that was used ('dev' if using current dev branch)
2.2.0.0

### PR DESCRIPTION
**Pull request by mcbobke**
#### Pull Request (PR) description
`Get-TargetResource` for `xWebsite` and `xIISLogging` return a hashtable that includes the `LogFlags` property. It is cast to an array but is not split which results in an array with a single String value inside of all LogFlags separated by commas. This fix correctly splits the string before casting to an Array.

#### This Pull Request (PR) fixes the following issues
- Fixes #405 

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md.
- [ ] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/440)

### CODE REVIEW

**Comment by mcbobke** [comment]
Tests and changelog still need to be updated.

**Comment by mcbobke** [comment]
I'd appreciate some guidance on writing the tests for this PR. `Get-WebConfiguration` is mocked to return the `$MockLogOutput` hashtable for `xIISLogging`; `Get-Website` is mocked to return the `$MockWebsite` hashtable for `xWebsite`. This consequently works around the bug that is being fixed by this pull request as the `logExtFileFlags` property already contains the expected array.

What would be the best way to cover this with tests?

**Comment by johlju** [comment]
There have been a few busy days, but back on reviewing this now.

**Comment by johlju** [comment]
No need to squash commits, I usually squash all the commits when I merge the PR.

**Comment by johlju** [comment]
@mcbobke Sorry it took so long for me to get back to this. Long days at the day job. and family and friends taking up time. Just waiting for the tests to pass and I will merge this one.

**Comment by mcbobke** [comment]
Completely understandable, thanks for the assistance with this one! :)

**Pull request merged**
