### PR TITLE
xWebSite: adding support for Site Id in xWebSite

### LINKED ISSUE #396: xWebAdministration: xWebSite: Impossible to set Site ID
#### Details of the scenario you tried and the problem that is occurring
There is no property to set the ID of a site while creating a WebSite with xWebSite ressource.

#### Suggested solution to the issue
Add a "ID" property in the ressource so we can specify the site ID.

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
# insert configuration here
```

#### Version of the DSC module that was used ('dev' if using current dev branch)
 'xWebAdministration' -ModuleVersion "2.0.0.0"

### PR DESCRIPTION
**Pull request by csharmath**
#### Pull Request (PR) description
Adding SiteId to the xWebSite resource allowing setting the desired IIS site Id.
As per comments on the original issue #396 SiteId is being used instead of Id to avoid potential future conflicts or confusions.

#### This Pull Request (PR) fixes the following issues
    - Fixes #396

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the README.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [x] Resource documentation added/updated in README.md.
- [x] Resource parameter descriptions added/updated in README.md, schema.mof
      and comment-based help.
- [x] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [x] Examples appropriately added/updated.
- [x] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwebadministration/415)

### CODE REVIEW

**Comment by csharmath** [comment]
I've asked my employer about the CLA, once I get a go ahead will sign.

* I didn't have a chance yet to check how the unit and integration tests could work and what would be needed to cover this new field. Happy to work on that as well.
* the comment based help is already incomplete, so I skipped adding this new property. Perhaps another new issue could be added for that?
* haven't seen any localization

**Comment by regedit32** [comment]
@csharmath Thanks for opening a PR for this issue, this will be a great enhancement to the resource.  

This PR will need to include tests to cover the changes before we start reviewing.  However, I did glance over it and noticed `Get-TargetResource` wasn't updated to return the new SiteId property.  Get-TargetResource should return all properties defined in the schema.mof.

You're right about the resource lacking localization, that should be a separate PR.  For the comment-based help, I think we should update accordingly as we add new parameters, but not necessarily go back and add prior existing parameter help.

**Comment by csharmath** [comment]
>However, I did glance over it and noticed `Get-TargetResource` wasn't updated to return the new SiteId property. Get-TargetResource should return all properties defined in the schema.mof.

Fixed

> You're right about the resource lacking localization, that should be a separate PR. For the comment-based help, I think we should update accordingly as we add new parameters, but not necessarily go back and add prior existing parameter help.

Fixed

>This PR will need to include tests to cover the changes before we start reviewing

Just added the unit and integration test changes. Writing the unit test helped me to discover a bug, so 
that's a good thing.

**Comment by csharmath** [comment]
@regedit32  let me know if there is anything else.

**Pull request merged**
